Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-11, with the labels that each got.

#599 585-be-filter-by-seennot_seen-not-working
  back/openapi.yaml
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/middleware/validate.ts
  back/src/openapi/routes/resources/get.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: bug, backend

#605 597-be-check-why-userVote-0-at-get-fav-resources
  back/src/__tests__/resources/favorites.test.ts
  back/src/controllers/resources/getFavoriteResources.ts
Labels: bug, backend

#606 move all fetch mutations to hooks with mutations
  front/src/__mocks__/handlers.ts
  front/src/__tests__/hooks/useCreateResource.test.tsx
  front/src/__tests__/hooks/useLogin.test.tsx
  front/src/__tests__/hooks/useManageTopic.test.tsx
  front/src/__tests__/hooks/useRegister.test.tsx
  front/src/__tests__/hooks/useUpdateResource.test.tsx
  front/src/components/organisms/Login.tsx
  front/src/components/organisms/Register.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/TopicsManagerBoard.tsx
  front/src/helpers/fetchers.ts
  front/src/hooks/index.ts
  front/src/hooks/useCreateResource.tsx
  front/src/hooks/useLogin.tsx
  front/src/hooks/useManageTopic.tsx
  front/src/hooks/useRegister.tsx
  front/src/hooks/useUpdateResource.tsx
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: frontend

#609 update user types to resolve duplicate name conflict
  front/src/hooks/useGetUsers.tsx
  front/src/pages/AccountAdim.tsx
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: bug, frontend

#600 586 send post request with seen resource when clicked on the title and logged in
  front/src/__mocks__/handlers.ts
  front/src/__tests__/molecules/ResourceTitleLink.test.tsx
  front/src/components/molecules/ResourceTitleLink.tsx
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/constants/urls.ts
  front/src/helpers/fetchers.ts
  front/src/types/types.tsx
Labels: frontend

#608 603-be-add-userid-in-getme-response
  back/openapi.yaml
  back/src/__tests__/auth/me.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/openapi/routes/auth/me.ts
  back/src/schemas/index.ts
  back/src/schemas/users/userGetSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#611 588 febug fix sort by date and votes count
  front/src/__tests__/hooks/useSortByVotes.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/hooks/useSortByVotes.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend

#568 533-fe-manage-users-modal
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/organisms/UsersManager.test.tsx
  front/src/__tests__/pages/AccountAdmin.test.tsx
  front/src/components/molecules/Tabs/Tabs.tsx
  front/src/components/organisms/AccountAdim.tsx
  front/src/components/organisms/SettingsManager.tsx
  front/src/components/organisms/UsersManager.tsx
  front/src/constants/paths.ts
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/main.tsx
  front/src/pages/index.ts
Labels: enhancement, frontend

#612 610 be getresourcesbyid me returning incorrect uservote & isfavorite
  back/src/__tests__/resources/me.test.ts
  back/src/controllers/resources/getResourcesById.ts
  back/src/controllers/resources/getResourcesByUserId.ts
Labels: bug, backend

#621 616-be-getresourcesme-add-userid-flat-nested-array
  back/openapi.yaml
  back/src/__tests__/resources/me.test.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/helpers/transformResourceToAPI.ts
  back/src/openapi/routes/resources/me.ts
  back/src/schemas/resource/resourceGetSchema.ts
Labels: bug, backend

#617 615 febug remove usuaris tab for mentor roles
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/organisms/UsersManager.test.tsx
  front/src/components/organisms/SettingsManager.tsx
  front/src/components/organisms/UsersManager.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
Labels: bug, frontend

#623 613-fix mobile styles
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend

#624 622-be-bug-resolve-validation-error-on-patch-users-endpoint
  back/openapi.yaml
  back/src/__tests__/users/patchUser.test.ts
  back/src/helpers/errors.ts
  back/src/middleware/errorMiddleware.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/authMiddleware.ts
  back/src/openapi/routes/auth/login.ts
  back/src/openapi/routes/auth/register.ts
  back/src/openapi/routes/favorites/put.ts
  back/src/openapi/routes/resources/get.ts
  back/src/openapi/routes/resources/id.ts
  back/src/openapi/routes/users/patch.ts
  back/src/openapi/routes/vote/vote.ts
  back/src/schemas/users/userPatchSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: bug, backend

#601 000-dockerize-apps
  .github/workflows/back-deploy-dev.yml
  .github/workflows/build_back.yml
  .github/workflows/build_front.yml
  .github/workflows/front-deploy-dev.yml
  .github/workflows/front-release.yml
  .github/workflows/pr_check_back.yml
  .github/workflows/pr_check_front.yml
  .github/workflows/schemas-package.yml
  .github/workflows/ship_packages_schemas.yml
  CHANGELOG_SAMPLE.md
  README.md
  back/CHANGELOG.md
  back/package.json
  front/CHANGELOG.md
  front/package.json
  scripts/check_changelog.sh
  scripts/check_version.sh
Labels: enhancement

#638 637 Fix password validation and error-message
  packages/schemas/CHANGELOG.md
  packages/schemas/package.json
  packages/schemas/src/Register.ts
Labels: bug, dependencies

#653 584-fe-add-favorites-widget
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/atoms/BackButton.test.tsx
  front/src/__tests__/atoms/Counter.test.tsx
  front/src/__tests__/context/AuthProvider.test.tsx
  front/src/__tests__/hooks/useGetResourcesByUser.test.tsx
  front/src/__tests__/molecules/CardProfile.test.tsx
  front/src/__tests__/molecules/FavoritesIcon.test.tsx
  front/src/__tests__/molecules/ResourceTitleLink.test.tsx
  front/src/__tests__/molecules/UserButton.test.tsx
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/__tests__/organisms/CardResource.test.tsx
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/__tests__/organisms/MyResources.test.tsx
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  front/src/__tests__/organisms/UserProfileResourcesWidget.test.tsx
  front/src/__tests__/organisms/UsersManager.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/__tests__/pages/UserProfile.test.tsx
  front/src/components/atoms/BackButton.tsx
  front/src/components/atoms/Counter.tsx
  front/src/components/atoms/UserImage.tsx
  front/src/components/molecules/CardProfile.tsx
  front/src/components/molecules/FavoritesIcon.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/UserProfileResourcesWidget.tsx
  front/src/components/organisms/VotesDateController.tsx
  front/src/components/organisms/index.ts
  front/src/context/AuthProvider.tsx
  front/src/helpers/fetchers.ts
  front/src/hooks/index.ts
  front/src/hooks/useGetResourcesByUser.tsx
  front/src/hooks/useSortByDate.tsx
  front/src/hooks/useSortByVotes.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
  front/src/pages/UserProfile.tsx
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: frontend

#649 598 be modify resources get controller to accept an array of topicids
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: bug, backend

#664 662-fe-update-category-icons
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/assets/icons/index.ts
  front/src/assets/icons/laravel.svg
  front/src/components/organisms/CategoriesList.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
  front/vite.config.ts
Labels: frontend

#648 628-be-sso-update-swagger-register
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/auth/register.test.ts
  sso/src/app.ts
  sso/src/controllers/auth/registerController.ts
  sso/src/controllers/user/index.ts
  sso/src/openapi/routes/index.ts
  sso/src/openapi/routes/register.ts
  sso/src/routes/authRoutes.ts
  sso/src/routes/index.ts
  sso/src/routes/userRoutes.ts
  sso/src/schemas/auth/loginSchema.ts
  sso/src/schemas/auth/registerSchema.ts
  sso/src/schemas/auth/userSchema.ts
  sso/src/schemas/index.ts
  sso/src/schemas/passwordRegex.ts
Labels: backend

#666 642-BUG-FIX-FE Remove border radius by %
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/organisms/Navbar.tsx
Labels: bug, frontend

#663 589-be-implement-by-name-query-filters
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: backend

#677 674-fe-bug-fix-userprofile-error-when-user-has-no-resources
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/pages/UserProfile.tsx
Labels: bug, frontend

#678 636 be sso implement testing and API documentation for post tokens validate endpoint
  sso/CHANGELOG.md
  sso/db/init.sql
  sso/openapi.yaml
  sso/package.json
  sso/src/__tests__/auth/login.test.ts
  sso/src/__tests__/auth/register.test.ts
  sso/src/__tests__/globalSetup.ts
  sso/src/__tests__/token/validate.test.ts
  sso/src/controllers/auth/loginController.ts
  sso/src/controllers/auth/registerController.ts
  sso/src/controllers/token/validate.ts
  sso/src/openapi/components/errorSchemas.ts
  sso/src/openapi/components/responses.ts
  sso/src/openapi/routes/auth/login.ts
  sso/src/openapi/routes/auth/register.ts
  sso/src/openapi/routes/index.ts
  sso/src/openapi/routes/token/validate.ts
  sso/src/routes/authRoutes.ts
  sso/src/routes/tokenRoutes.ts
  sso/src/schemas/auth/loginSchema.ts
  sso/src/schemas/token/tokenSchema.ts
  sso/src/schemas/token/validateSchema.ts
  sso/src/utils/auth.ts
Labels: documentation, backend

#683 633 fe bug fix AdminAccount style for medium and small devices
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/AccountAdmin.test.tsx
  front/src/__tests__/organisms/UsersManager.test.tsx
  front/src/components/organisms/AccountAdim.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
Labels: bug, frontend

#687 685-be-fix-resources-filter-by-topic
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: bug, backend

#679 587-new-resource-search-bar-UI-implementation
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
Labels: frontend

#690 688 be fix search param get resources
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: bug, backend

#693 682-be-sso-implement-itinerary-table-and-update-user-table-schema
  sso/CHANGELOG.md
  sso/db/init.sql
  sso/openapi.yaml
  sso/package.json
  sso/src/__tests__/auth/register.test.ts
  sso/src/__tests__/globalSetup.ts
  sso/src/__tests__/itinerary/get.test.ts
  sso/src/app.ts
  sso/src/controllers/auth/registerController.ts
  sso/src/controllers/itinerary/get.ts
  sso/src/middleware/errorMiddleware.ts
  sso/src/openapi/components/responses.ts
  sso/src/openapi/routes/auth/register.ts
  sso/src/openapi/routes/index.ts
  sso/src/openapi/routes/itinerary/get.ts
  sso/src/routes/index.ts
  sso/src/routes/itinerary.ts
  sso/src/routes/routes.ts
  sso/src/schemas/auth/registerSchema.ts
  sso/src/schemas/auth/userSchema.ts
  sso/src/schemas/itinerary/itineraryGetSchema.ts
  sso/src/schemas/itinerary/itinerarySchema.ts
  sso/src/utils/errors.ts
Labels: documentation, enhancement, backend

#696 665-fefix-category-page-details-without-resources
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/VotesDateController.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/UserProfileResourcesWidget.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
Labels: bug, frontend

#700 699-Update-categories-logos-and-icons
  front/CHANGELOG.md
  front/package.json
  front/src/assets/icons/angular.svg
  front/src/assets/icons/bbdd.svg
  front/src/assets/icons/data-science.svg
  front/src/assets/icons/index.ts
  front/src/assets/icons/it-logo.svg
  front/src/assets/icons/java.svg
  front/src/assets/icons/javascript.svg
  front/src/assets/icons/nodejs-logo.svg
  front/src/assets/icons/php.svg
  front/src/assets/icons/react.svg
  front/src/components/organisms/CategoriesList.tsx
Labels: frontend

#702 672-febug-fix-patch-user
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/hooks/useUpdateUserStatus.test.tsx
  front/src/__tests__/organisms/AccountAdmin.test.tsx
  front/src/components/organisms/AccountAdmin.tsx
  front/src/components/organisms/UsersManager.tsx
  front/src/components/organisms/index.ts
  front/src/helpers/fetchers.ts
  front/src/hooks/index.ts
  front/src/hooks/useUpdateUserStatus.tsx
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: bug, frontend

#704 694-fe-implement-corrections-in-multilingual-copies
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/molecules/AccessModalContent.test.tsx
  front/src/__tests__/molecules/CardProfile.test.tsx
  front/src/__tests__/molecules/StatusFilterWidget.test.tsx
  front/src/__tests__/molecules/TypesFilterWidget.test.tsx
  front/src/__tests__/organisms/EditResource.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/__tests__/pages/UserProfile.test.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/molecules/AccessModalContent.tsx
  front/src/components/molecules/StatusFilterWidget.tsx
  front/src/components/molecules/TypesFilterWidget.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
Labels: frontend

#703 589 fe implement search by name query + filters
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/organisms/Search.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/Search.tsx
  front/src/components/organisms/index.ts
  front/src/helpers/filters.ts
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
  front/src/types/types.tsx
Labels: enhancement, frontend

#715 646-febugfix-equal-width
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/components/organisms/CardResourceLink.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend

#719 718 add-favicon-and-remove-unused-icons
  front/CHANGELOG.md
  front/index.html
  front/package.json
  front/src/assets/icons/favicon.png
  front/src/assets/icons/index.ts
  front/src/assets/icons/laravel.svg
  front/src/assets/icons/python.svg
  front/src/assets/icons/spring.svg
  front/src/assets/icons/vue.svg
  front/src/components/organisms/CategoriesList.tsx
  front/src/constants/categories.ts
Labels: frontend

#724 712-fe-add-hover-effect-to-clickable-items
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/molecules/FavoritesIcon.test.tsx
  front/src/__tests__/organisms/CardResource.test.tsx
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/__tests__/organisms/UserProfileResourcesWidget.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/atoms/Icon.tsx
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/VotesDateController.tsx
  front/src/locales/cat.json
  front/src/pages/Category.tsx
Labels: enhancement, frontend

#728 713 febug fix initial values in editresource
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/molecules/TypesFilterWidget.tsx
  front/src/components/organisms/ResourceForm.tsx
Labels: bug, frontend

#716 675-be-modify-getfavorites-response
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/src/__tests__/resources/favorites.test.ts
  back/src/controllers/resources/getFavoriteResources.ts
  back/src/helpers/transformResourceToAPI.ts
  back/src/schemas/resource/resourceFavoriteSchema.ts
Labels: enhancement, backend

#736 731 febug filter topics on edit resource by slug
  front/CHANGELOG.md
  front/package.json
  front/src/components/organisms/EditResource.tsx
Labels: bug, frontend

#738 723-fe-bug-fix-topics-list-updating-when-managing-topics
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/TopicsManagerBoard.tsx
  front/src/hooks/useGetTopics.tsx
  front/src/hooks/useManageTopic.tsx
Labels: bug, frontend
