Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-10, with the labels that each got.

#506 500-be-drop-created_at-and-updated_at-from-viewed_resource-table
  back/prisma/migrations/20230928091538_remove_created_at_and_updated_at/migration.sql
  back/prisma/schema.prisma
Labels: backend

#516 515-be-remove-email-from-resources-response
  back/openapi.yaml
  back/src/controllers/index.ts
  back/src/controllers/resources/get.ts
  back/src/controllers/resources/getResourcesById.ts
  back/src/controllers/resources/getResourcesByTopic.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/openapi/routes/resources/get.ts
  back/src/schemas/resource/resourceGetSchema.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: bug, backend

#518 484-be-error-filtering-resources-by-topic-getresou
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
Labels: backend

#523 514-fe-add-message-for-special-characters-in-password-at-register
  front/src/__tests__/organisms/Register.test.tsx
  front/src/__tests__/organisms/UserAccesHome.test.tsx
  front/src/components/organisms/Login.tsx
  front/src/components/organisms/Register.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
Labels: bug, frontend

#521 505-be-update-get-resources-endpoint
  back/openapi.yaml
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/controllers/resources/getFavoriteResources.ts
  back/src/controllers/resources/getResourcesById.ts
  back/src/controllers/resources/getResourcesByTopic.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/helpers/addVoteCountToResource.ts
  back/src/helpers/transformResourceToAPI.ts
  back/src/middleware/authenticate.ts
  back/src/middleware/index.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/voteCountSchema.ts
Labels: backend

#526 525-be-update-get-vote-endpoint
  back/openapi.yaml
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/vote/vote.test.ts
  back/src/controllers/index.ts
  back/src/controllers/vote/get.ts
  back/src/controllers/vote/put.ts
  back/src/helpers/transformResourceToAPI.ts
  back/src/openapi/routes/vote/vote.ts
  back/src/routes/index.ts
  back/src/routes/vote.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/schemas/voteCountSchema.ts
Labels: backend

#536 475-keep vote status when user is logged in
  front/src/__mocks__/handlers.ts
  front/src/__mocks__/handlers/vote.ts
  front/src/__tests__/context/store/reducer.test.tsx
  front/src/__tests__/hooks/useSortByDate.test.tsx
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/context/store/types.tsx
  front/src/hooks/useGetResources.tsx
Labels: frontend

#535 522-fe-bug-consistent-add-button-behavior
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: bug, frontend

#537 533-be-fe-bug-handle-cookie-expired-on-getresources
  back/openapi.yaml
  back/src/__tests__/auth/me.test.ts
  back/src/__tests__/favorites/putFavoriteByUserId.test.ts
  back/src/__tests__/helpers/checkInvalidToken.ts
  back/src/__tests__/media/media.test.ts
  back/src/__tests__/resources/create.test.ts
  back/src/__tests__/resources/favorites.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/resources/me.test.ts
  back/src/__tests__/resources/patch.test.ts
  back/src/__tests__/topics/createTopic.test.ts
  back/src/__tests__/topics/patchTopic.test.ts
  back/src/__tests__/users/get.test.ts
  back/src/__tests__/users/patchUser.test.ts
  back/src/__tests__/vote/vote.test.ts
  back/src/controllers/auth/loginController.ts
  back/src/middleware/authenticate.ts
  back/src/middleware/errorMiddleware.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/authMiddleware.ts
  back/src/openapi/routes/auth/login.ts
  back/src/openapi/routes/auth/me.ts
  back/src/openapi/routes/favorites/put.ts
  back/src/openapi/routes/media.ts
  back/src/openapi/routes/resources/create.ts
  back/src/openapi/routes/resources/favorites.ts
  back/src/openapi/routes/resources/get.ts
  back/src/openapi/routes/resources/me.ts
  back/src/openapi/routes/resources/patch.ts
  back/src/openapi/routes/topics/create.ts
  back/src/openapi/routes/topics/patch.ts
  back/src/openapi/routes/users/get.ts
  back/src/openapi/routes/users/patch.ts
  back/src/openapi/routes/vote/vote.ts
Labels: bug, backend

#542 489-2.0-fix-create-resource
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend

#540 534-be-add-user-fav-as-isfav-param-in-get-if-auth
  back/openapi.yaml
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/get.ts
  back/src/helpers/transformResourceToAPI.ts
  back/src/schemas/resource/resourceGetSchema.ts
Labels: enhancement, backend

#531 470-fe-add-favorites-option-to-resource-card
  front/src/__mocks__/handlers.ts
  front/src/__tests__/context/store/reducer.test.tsx
  front/src/__tests__/hooks/useGetFavorites.test.tsx
  front/src/__tests__/molecules/FavoritesIcon.test.tsx
  front/src/__tests__/organisms/CardResource.test.tsx
  front/src/__tests__/organisms/CardResourceLink.test.tsx
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/__tests__/pages/UserProfile.test.tsx
  front/src/components/molecules/FavoritesIcon.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/constants/urls.ts
  front/src/context/store/types.tsx
  front/src/helpers/fetchers.ts
  front/src/hooks/useGetFavorites.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/UserProfile.tsx
Labels: frontend

#543 524-handle-text-overflow-in-resource-cards-for-small-screens
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/pages/Category.tsx
Labels: frontend

#544 466 design notifications context
  front/src/__tests__/molecules/Notifications/Notification.test.tsx
  front/src/__tests__/molecules/Notifications/Notifications.test.tsx
  front/src/__tests__/molecules/Notifications/context.test.tsx
  front/src/__tests__/molecules/Notifications/reducer.test.ts
  front/src/__tests__/molecules/Notifications/useNotifications.test.ts
  front/src/__tests__/test-utils.tsx
  front/src/components/molecules/CardProfile.tsx
  front/src/components/molecules/Notifications/Notification.tsx
  front/src/components/molecules/Notifications/Notifications.tsx
  front/src/components/molecules/Notifications/context.tsx
  front/src/components/molecules/Notifications/index.ts
  front/src/components/molecules/Notifications/reducer.ts
  front/src/components/molecules/Notifications/types.ts
  front/src/components/molecules/Notifications/useNotifications.ts
  front/src/main.tsx
  front/src/pages/Category.tsx
Labels: frontend

#554 499-be-bug-seen-and-not-seen-not-implemented-not-working-properly
  back/openapi.yaml
  back/prisma/migrations/20231016192612_remove_status/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/favorites/putFavoriteByUserId.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/mocks/resources.ts
  back/src/__tests__/resources/create.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/resources/patch.test.ts
  back/src/__tests__/seen/create.test.ts
  back/src/controllers/index.ts
  back/src/controllers/resources/get.ts
  back/src/controllers/resources/getFavoriteResources.ts
  back/src/controllers/seen/create.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/paramSchemas.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/id.ts
  back/src/openapi/routes/seen/create.ts
  back/src/openapi/routes/vote/vote.ts
  back/src/routes/index.ts
  back/src/routes/routes.ts
  back/src/routes/seen.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/server.ts
Labels: bug, backend

#556 497-fe-add-topics-modal
  front/src/__mocks__/handlers.ts
  front/src/__tests__/hooks/useGetTopics.test.tsx
  front/src/__tests__/molecules/TopicsEditableItem.test.tsx
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  front/src/components/molecules/Tabs/Tabs.tsx
  front/src/components/molecules/TopicsEditableItem.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/SettingsManager.tsx
  front/src/components/organisms/TopicsManagerBoard.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/constants/urls.ts
  front/src/context/AuthProvider.tsx
  front/src/helpers/fetchers.ts
  front/src/hooks/index.ts
  front/src/hooks/useGetTopics.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: frontend

#562 495-2-be-add-media-to-category
  back/prisma/migrations/20231019081802_add_media_to_category/migration.sql
  back/prisma/schema.prisma
Labels: backend

#557 494-be-add-post-patch-to-categories
  back/openapi.yaml
  back/src/__tests__/categories/categories.test.ts
  back/src/__tests__/categories/createCategory.test.ts
  back/src/__tests__/categories/getCategories.test.ts
  back/src/__tests__/categories/patchCategory.test.ts
  back/src/controllers/categories/create.ts
  back/src/controllers/categories/get.ts
  back/src/controllers/categories/patch.ts
  back/src/controllers/index.ts
  back/src/openapi/routes/categories/create.ts
  back/src/openapi/routes/categories/get.ts
  back/src/openapi/routes/categories/patch.ts
  back/src/openapi/routes/index.ts
  back/src/routes/categoriesRouter.ts
  back/src/schemas/category/categoryCreateSchema.ts
  back/src/schemas/category/categoryPatchSchema.ts
  back/src/schemas/category/categorySchema.ts
  back/src/schemas/categorySchema.ts
  back/src/schemas/index.ts
Labels: backend

#563 497-fe-add-topics-modal
  front/src/components/organisms/Navbar.tsx
Labels: frontend

#572 564-Add button in NavBar to Tablet size
  front/package-lock.json
  front/package.json
  front/src/components/organisms/Navbar.tsx
Labels: frontend

#567 [BE] 328 include category id into resource
  back/prisma/data/resources.ts
  back/prisma/migrations/20231010092240_add_resource_category/migration.sql
  back/prisma/schema.prisma
  back/prisma/seed.ts
  back/src/__tests__/mocks/resources.ts
  back/src/__tests__/resources/patch.test.ts
  back/src/__tests__/vote/vote.test.ts
  back/src/controllers/resources/createResourceController.ts
  back/src/controllers/resources/getFavoriteResources.ts
Labels: backend

#576 resource category_id set to NOT_NULL
  back/prisma/migrations/20231025080336_resource_category_id_not_null/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/favorites/putFavoriteByUserId.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/resources/byId.test.ts
  back/src/__tests__/resources/byTopic.test.ts
  back/src/__tests__/resources/create.test.ts
  back/src/__tests__/resources/favorites.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/resources/me.test.ts
  back/src/__tests__/seen/create.test.ts
Labels: backend

#580 579-be-bug-error-running-npm-run-up-database-connection-issues-and-mi…
  scripts/up.sh
  scripts/utils.sh
Labels: bug, backend

#555 Prevented voteCounter from making too many fetch vote requests
  front/src/__mocks__/handlers.ts
  front/src/__mocks__/handlers/vote.ts
  front/src/__tests__/helpers/updateCachedVoteCount.test.ts
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/__tests__/organisms/CardResource.test.tsx
  front/src/__tests__/organisms/CardResourceLink.test.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/helpers/fetchers.ts
  front/src/helpers/index.ts
  front/src/helpers/updateCachedVoteCount.ts
  front/src/hooks/useGetVotes.tsx
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: bug, frontend

#571 224-2-be-add-avatar-field-to-getme-response
  back/openapi.yaml
  back/prisma/migrations/20231024080440_add_avatar_id_to_user/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/auth/me.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/users/get.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/controllers/auth/register.ts
  back/src/controllers/media/postMediaController.ts
  back/src/controllers/users/patch.ts
  back/src/helpers/processMedia.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#577 552-fe-add-cache-management-for-favorites
  front/src/__mocks__/handlers.ts
  front/src/__tests__/molecules/FavoritesIcon.test.tsx
  front/src/components/molecules/FavoritesIcon.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/constants/urls.ts
  front/src/helpers/fetchers.ts
Labels: frontend

#594 393-docker-compose-v1
  back/.dockerignore
  back/.env
  back/.eslintrc
  back/Dockerfile
  back/package.json
  back/src/prisma/client.ts
  back/tsconfig.eslint.json
  back/tsconfig.json
  docker-compose.yml
  front/.dockerignore
  front/Dockerfile
  front/nginx.conf.template
  packages/schemas/package.json
Labels: enhancement, frontend, backend

#592 590-be-fix-post-resource-endpoint
  back/openapi.yaml
  back/src/schemas/favorites/favoritePutSchema.ts
  back/src/schemas/resource/resourceCreateSchema.ts
  back/src/schemas/resource/resourceSchema.ts
Labels: backend

#593 591-fe-bug-add-categoryid-to-create-resource
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/organisms/ResourceForm.tsx
Labels: bug, frontend

#581 551-fe-fix-mobile-styles
  front/src/components/atoms/HamburgerMenu.tsx
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend
