Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-06, with the labels that each got.

#278 277-added logo to category
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: frontend

#289 248 add topics widget for filtering
  front/src/__mocks__/handlers.ts
  front/src/__tests__/atoms/Radio.test.tsx
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/components/atoms/Radio.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/components/organisms/index.ts
  front/src/constants/urls.ts
  front/src/pages/Category.tsx
Labels: frontend

#290 modificado Logo
  front/src/assets/icons/index.ts
  front/src/assets/icons/it-logo.png
  front/src/assets/icons/it-logo.svg
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: frontend

#292 288 bebug fix favorites resources shape
  back/openapi.yaml
  back/src/__tests__/favorites/favorites.test.ts
  back/src/controllers/favoriteController.ts
  back/src/openapi/routes/favorites.ts
Labels: bug, backend

#291 264 fe get topics when navigating to a category
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/CategoriesList.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/test-utils.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/ResourcesList.tsx
  front/src/components/organisms/index.ts
  front/src/constants/urls.ts
  front/src/pages/Category.tsx
Labels: frontend

#295 Fixed typography
  front/src/__tests__/atoms/Button.test.tsx
  front/src/__tests__/atoms/Label.test.tsx
  front/src/components/atoms/Button.tsx
  front/src/components/atoms/Dropdown.tsx
  front/src/components/atoms/Input.tsx
  front/src/components/atoms/Label.tsx
  front/src/components/atoms/Link.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/atoms/Textarea.tsx
  front/src/components/atoms/ValidationMessage.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/pages/Login.tsx
Labels: bug, frontend

#298 Enabled endpoint for resource type
  back/openapi.yaml
  back/src/__tests__/types/types.test.ts
  back/src/controllers/index.ts
  back/src/controllers/type/typeController.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/types.ts
  back/src/routes/index.ts
  back/src/routes/routes.ts
  back/src/routes/typesRouter.ts
  back/src/server.ts
Labels: backend

#299 273-2-be-make-getresources-accept-status-seen-not-seen
  back/.eslintrc
  back/openapi.yaml
  back/prisma/migrations/20230619083843_resource_add_status/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/mocks/resources.ts
  back/src/__tests__/resources/create.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: backend

#305 304-be-correct-missing-optional-on-resourceSchema-
  back/openapi.yaml
  back/src/schemas/resource/resourceSchema.ts
Labels: backend

#303 302-fe-add-status-filter-widget-frontend-new
  front/src/__tests__/molecules/StatusFilterWidget.test.tsx
  front/src/components/molecules/StatusFilterWidget.tsx
  front/src/components/molecules/index.ts
  front/src/pages/Category.tsx
Labels: frontend

#209 174 publish resources
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/CategoriesList.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/__tests__/pages/Resource.test.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/constants/categories.ts
  front/src/constants/index.ts
  front/src/constants/paths.ts
  front/src/constants/urls.ts
  front/src/main.tsx
  front/src/pages/AddResource.tsx
  front/src/pages/Login.tsx
  front/src/pages/Resource.tsx
  front/src/pages/index.ts
Labels: frontend

#306 285-update-frontpage
  front/src/__tests__/molecules/CardHome.test.tsx
  front/src/__tests__/organisms/Login.test.tsx
  front/src/__tests__/organisms/Register.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/molecules/CardHome.tsx
  front/src/components/molecules/CategoryBlock.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/Login.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/Register.tsx
  front/src/constants/paths.ts
  front/src/main.tsx
  front/src/pages/Home.tsx
  front/src/pages/Resource.tsx
  front/src/pages/index.ts
Labels: frontend

#307 251 add my favorite widget
  front/src/__mocks__/handlers.ts
  front/src/__tests__/atoms/Link.test.tsx
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/components/atoms/Link.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/index.ts
  front/src/constants/urls.ts
  front/src/pages/Category.tsx
Labels: frontend

#310 Changed create resource route
  back/openapi.yaml
  back/src/__tests__/resources/create.test.ts
  back/src/openapi/routes/resources/create.ts
  back/src/routes/resourcesRouter.ts
Labels: backend

#317 315-updated create resource URL
  front/src/components/organisms/ResourceForm.tsx
  front/src/constants/urls.ts
Labels: bug, frontend

#318 312-fe-use-loginregister-modals-on-favoritesmy-resources
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
Labels: frontend

#319 313-reload-page-when-succesful-login
  front/src/components/organisms/Login.tsx
Labels: frontend

#321 fix navigation bug
  front/src/components/organisms/Navbar.tsx
Labels: bug, frontend

#320 316-delete-mocks
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/organisms/index.ts
  front/src/pages/Category.tsx
  front/src/pages/Resource.tsx
  front/src/pages/index.ts
Labels: frontend

#327 323-fix my resources bug
  front/src/components/organisms/MyResources.tsx
Labels: bug, frontend
