Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-04, with the labels that each got.

#74 73 [BE] improving landing documentation for backend
  back/Readme.md
Labels: documentation, backend

#64 5 add login form
  back/prisma/migrations/migration_lock.toml
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/pages/Login.test.tsx
  front/src/__tests__/utils/validateID.test.ts
  front/src/components/molecules/InputGroup.tsx
  front/src/pages/ErrorPage.tsx
  front/src/pages/Login.tsx
  front/src/theme/dimensions.ts
  front/src/theme/index.ts
  front/src/utils/index.ts
  front/src/utils/validateID.ts
Labels: frontend

#78 77 [BE] expand docs to link with vitest and prisma documentation
  back/Readme.md
Labels: documentation, backend

#79 75-docsfeinclude-readmemd-in-the-fe
  front/README.md
  package-lock.json
Labels: documentation, frontend

#71 [BE] Add registration endpoint [route + logic] (#38)
  back/.gitignore
  back/package.json
  back/prisma/migrations/20230322141331_add_dni_field/migration.sql
  back/prisma/migrations/20230327144331_init/migration.sql
  back/prisma/migrations/20230329112253_init/migration.sql
  back/prisma/seed.ts
  back/src/__tests__/auth/login.test.ts
  back/src/__tests__/auth/register.test.ts
  back/src/controllers/index.ts
  back/src/controllers/loginController.ts
  back/src/controllers/registerController.ts
  back/src/helpers/errors.ts
  back/src/middleware/errorMiddleware.ts
  back/src/prisma/middleware/passwordMiddleware.ts
  back/src/routes/authRouter.ts
  back/src/schemas/UserLoginSchema.ts
  back/src/schemas/UserRegisterSchema.ts
  back/src/schemas/index.ts
  back/src/schemas/regex/passwordRegex.ts
Labels: backend

#72 67 create Select component
  front/package-lock.json
  front/src/__tests__/atoms/Select.test.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/atoms/index.ts
Labels: frontend

#70 53 add register form
  back/package-lock.json
  back/package.json
  front/package-lock.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/pages/Register.test.tsx
  front/src/components/atoms/Button.tsx
  front/src/pages/Register.tsx
Labels: frontend

#87 fe-80-create-selectgroup
  front/src/__tests__/molecules/SelectGroup.test.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/molecules/SelectGroup.tsx
  front/src/components/molecules/index.ts
Labels: frontend

#107 [BE] [DB] create resources table (#89)
  back/prisma/migrations/20230412110842_add_resource_topic/migration.sql
  back/prisma/migrations/migration_lock.toml
  back/prisma/schema.prisma
  back/prisma/seed.ts
  back/src/__tests__/database/seed.test.ts
  back/src/schemas/ResourceSchema.ts
  back/src/schemas/TopicSchema.ts
  back/src/schemas/index.ts
Labels: backend

#109 94 create Modal component
  front/src/__tests__/molecules/Modal.test.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/index.ts
  front/src/styles/dimensions.ts
Labels: frontend

#111 93 [be][db] create post method to create new resources
  back/src/__tests__/database/seed.test.ts
  back/src/__tests__/resources/resources.test.ts
  back/src/controllers/index.ts
  back/src/controllers/resourceController.ts
  back/src/middleware/authMiddleware.ts
  back/src/middleware/index.ts
  back/src/routes/index.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/CreateResourceSchema.ts
  back/src/schemas/index.ts
  back/src/server.ts
  front/src/components/molecules/index.ts
Labels: backend

#86 [BE] Add swagger to the routes (#16)
  back/openapi.yaml
  back/src/openapi/components/bearerAuth.ts
  back/src/openapi/components/cookieAuth.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/setCookieHeader.ts
  back/src/openapi/config.ts
  back/src/openapi/routes/auth/login.ts
  back/src/openapi/routes/auth/register.ts
  back/src/openapi/routes/authRouter.ts
  back/src/openapi/routes/index.ts
Labels: backend

#112 100 create restricted AccessModal
  .github/workflows/front-pr.yml
  front/.eslintrc
  front/src/__tests__/molecules/AccessModal.test.tsx
  front/src/assets/icons/lock-dynamic-color.svg
  front/src/components/molecules/AccessModal.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/index.ts
  front/tsconfig.json
Labels: frontend

#113 101 create textarea input and group
  front/src/__tests__/atoms/Textarea.test.tsx
  front/src/__tests__/molecules/TextareaGroup.test.tsx
  front/src/components/atoms/Textarea.tsx
  front/src/components/atoms/index.ts
  front/src/components/molecules/TextareaGroup.tsx
  front/src/components/molecules/index.ts
  front/src/pages/Home.tsx
Labels: frontend

#118 97 [BE] create handle for get categories
  back/src/__tests__/topics/topics.test.ts
  back/src/controllers/index.ts
  back/src/controllers/topicController.ts
  back/src/routes/index.ts
  back/src/routes/topicsRouter.ts
  back/src/server.ts
Labels: backend

#130 119 be convert prisma seed file to declarative
  back/prisma/data/resources.ts
  back/prisma/data/topics.ts
  back/prisma/data/users.ts
  back/prisma/seed.ts
  back/src/__tests__/auth/login.test.ts
  back/src/__tests__/database/seed.test.ts
  back/src/__tests__/resources/resources.test.ts
  back/src/prisma/client.ts
  back/src/prisma/middleware/index.ts
  back/src/prisma/middleware/passwordMiddleware.ts
  back/src/server.ts
Labels: backend

#131 99 be extend user schema to include role type
  back/prisma/migrations/20230417091552_init/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/auth/register.test.ts
  back/src/schemas/UserSchema.ts
Labels: backend

#137 102 [FE] CheckBox atom & tests
  front/src/__tests__/atoms/CheckBox.test.tsx
  front/src/components/atoms/CheckBox.tsx
  front/src/components/atoms/index.ts
  front/src/styles/dimensions.ts
Labels: frontend

#141 [BE][DB]-Media-model-created
  back/prisma/data/media.ts
  back/prisma/migrations/20230419063024_add_media/migration.sql
  back/prisma/schema.prisma
Labels: backend

#140 91-fe-create-categories-block (Home page mobile version)
  front/src/__tests__/molecules/CategoryBlock.test.tsx
  front/src/__tests__/organisms/CategoriesList.test.tsx
  front/src/__tests__/organisms/HowToHelpCard.test.tsx
  front/src/assets/icons/angular.svg
  front/src/assets/icons/data-science.svg
  front/src/assets/icons/index.ts
  front/src/assets/icons/javascript.svg
  front/src/assets/icons/new-folder-dynamic-color.svg
  front/src/assets/icons/react.svg
  front/src/assets/icons/vue.svg
  front/src/components/molecules/CardResourceHome.tsx
  front/src/components/molecules/CategoryBlock.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/HowToHelpCard.tsx
  front/src/components/organisms/ResourcesList.tsx
  front/src/components/organisms/index.ts
  front/src/constants/paths.ts
  front/src/main.tsx
  front/src/pages/AddResource.tsx
  front/src/pages/Home.tsx
  front/src/pages/Information.tsx
  front/src/pages/index.ts
  front/src/styles/FlexBox.ts
Labels: frontend

#150 92 create category page
  front/src/__tests__/molecules/AvatarInfo.test.tsx
  front/src/__tests__/molecules/Modal.test.tsx
  front/src/__tests__/pages/Resource.test.tsx
  front/src/assets/icons/arrow-down.svg
  front/src/assets/icons/edit-pen.svg
  front/src/assets/icons/index.ts
  front/src/assets/icons/profile-avatar.svg
  front/src/components/molecules/AvatarInfo.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/constants/paths.ts
  front/src/main.tsx
  front/src/pages/Resource.tsx
  front/src/pages/index.ts
Labels: frontend

#155 148 favorites db table
  back/prisma/migrations/20230422214032_add_favorites/migration.sql
  back/prisma/schema.prisma
Labels: backend

#153 147 BE getCategories
  back/openapi.yaml
  back/src/__tests__/categories/categories.test.ts
  back/src/controllers/categoryController.ts
  back/src/controllers/index.ts
  back/src/openapi/config.ts
  back/src/openapi/routes/auth/login.ts
  back/src/openapi/routes/auth/register.ts
  back/src/openapi/routes/categories.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/topics/category.ts
  back/src/openapi/routes/topics/topics.ts
  back/src/routes/authRouter.ts
  back/src/routes/categoriesRouter.ts
  back/src/routes/index.ts
  back/src/routes/resourcesRouter.ts
  back/src/routes/routes.ts
  back/src/routes/topicsRouter.ts
  back/src/server.ts
Labels: backend

#198 175 create molecule for resource title and description
  front/src/__tests__/molecules/ResourceTitleLink.test.tsx
  front/src/components/molecules/ResourceTitleLink.tsx
  front/src/components/molecules/index.ts
  front/src/pages/Home.tsx
  front/vite.config.ts
Labels: frontend

#203 181 be create getme endpoint
  back/openapi.yaml
  back/src/__tests__/auth/me.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/controllers/auth/loginController.ts
  back/src/controllers/auth/registerController.ts
  back/src/controllers/index.ts
  back/src/middleware/authMiddleware.ts
  back/src/openapi/components/cookieAuth.ts
  back/src/openapi/config.ts
  back/src/openapi/routes/auth/me.ts
  back/src/openapi/routes/index.ts
  back/src/routes/authRouter.ts
Labels: backend

#200 152-fe-add-checkbox-component-to-register-form
  front/src/__tests__/atoms/CheckBox.test.tsx
  front/src/components/atoms/CheckBox.tsx
  front/src/pages/Register.tsx
Labels: frontend

#192 180-started AuthProvider
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/context/AuthProvider.test.tsx
  front/src/__tests__/setup.ts
  front/src/context/AuthProvider.tsx
  front/src/main.tsx
  front/src/pages/Home.tsx
Labels: frontend

#207 add vote table
  back/prisma/migrations/20230428132132_add_vote/migration.sql
  back/prisma/schema.prisma
Labels: backend
