Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-07, with the labels that each got.

#335 322-fe-fix-spinner-and-error-on-favorite-resources
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/components/organisms/MyFavoritesList.tsx
Labels: frontend

#339 [FE] Error voting without login
  front/src/__tests__/atoms/Button.test.tsx
  front/src/__tests__/molecules/AccessModal.test.tsx
  front/src/__tests__/molecules/AccessModalContent.test.tsx
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/atoms/Button.tsx
  front/src/components/molecules/AccessModalContent.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/Login.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: frontend

#311 259-be-enable-recover-user-resources-by-categ-slug
  back/src/__tests__/resources/me.test.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/routes/resourcesRouter.ts
Labels: backend

#338 add denied login for inactive users
  back/src/__tests__/auth/login.test.ts
  back/src/__tests__/auth/me.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/controllers/auth/loginController.ts
Labels: bug

#345 test-cache
  .github/workflows/back-pr.yml
  .github/workflows/front-pr.yml
  back/openapi.yaml
  back/prisma/data/users.ts
  back/src/__tests__/database/seed.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/media/media.test.ts
  back/src/__tests__/resources/favorites.test.ts
  back/src/controllers/media/postMediaController.ts
  back/src/controllers/resources/getFavoriteResources.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/controllers/vote/voteController.ts
  back/src/middleware/authMiddleware.ts
  back/src/openapi/routes/resources/favorites.ts
  back/src/routes/resourcesRouter.ts
  back/vitest.config.ts
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/MyFavoritesList.test.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/constants/urls.ts
  front/vite.config.ts
Labels: frontend, backend

#334 329-category-breakpoint-desktop-to-mobile
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/pages/Category.tsx
Labels: frontend

#346 added logout endpoint
  back/openapi.yaml
  back/src/openapi/routes/auth/logout.ts
  back/src/openapi/routes/index.ts
Labels: backend

#353 342 specific error messages on login form
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/Login.test.tsx
  front/src/components/organisms/Login.tsx
Labels: frontend

#355 332 my resources mobile
  front/src/__tests__/organisms/MyResources.test.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/ResourceTitleLink.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
  front/vite.config.ts
Labels: frontend

#357 352-febug-make-layout-navigation-consistent
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/atoms/Radio.tsx
  front/src/components/molecules/CardHome.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/InputGroup.tsx
  front/src/components/organisms/Register.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
  front/src/styles/colors.ts
  front/vite.config.ts
Labels: bug, frontend

#362 287 edit resource
  back/.gitignore
  back/src/__tests__/resources/patch.test.ts
  back/src/controllers/resources/patchResource.ts
  back/src/openapi/routes/resources/patch.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/resource/resourceDeleteSchema.ts
  back/src/schemas/resource/resourcePatchSchema.ts
Labels: bug, backend

#360 351 sort resources by date
  front/src/components/organisms/ResourceCardList.tsx
Labels: enhancement, frontend

#359 350 be filter returned resources based on query params
  back/package-lock.json
  back/package.json
  back/src/controllers/resources/getResourcesController.ts
Labels: backend

#364 352-febug-make-layout-navigation-consistent
  front/src/components/atoms/Radio.tsx
  front/src/pages/Category.tsx
Labels: frontend

#361 348 fe fix votes putget
  front/src/__mocks__/handlers.ts
  front/src/__mocks__/handlers/vote.ts
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/constants/urls.ts
Labels: frontend

#380 368 add windows section
  back/Readme.md
Labels: backend

#382 update
  back/src/openapi/routes/index.ts
Labels: bug, backend

#367 336 implement logout
  front/src/components/organisms/Navbar.tsx
  front/src/constants/urls.ts
Labels: frontend

#385 370-be-create-new-role-mentor
  back/openapi.yaml
  back/prisma/data/users.ts
  back/prisma/migrations/20230710075330_add_user_role_mentor/migration.sql
  back/prisma/schema.prisma
  back/prisma/seed.ts
  back/src/__tests__/globalSetup.ts
  back/src/schemas/userSchema.ts
Labels: backend

#386 286 fe-edit-resource
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/__tests__/setup.ts
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/index.ts
  front/src/constants/urls.ts
Labels: frontend

#390 384 change sort order for resources
  front/src/__tests__/hooks/useSortByDate.test.tsx
  front/src/__tests__/organisms/ResourceCardList.test.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/hooks/useSortByDate.tsx
  front/src/pages/Category.tsx
Labels: enhancement, frontend

#404 375-be-create-post-patch-topics-routes-controller
  back/src/__tests__/setup.ts
  back/src/__tests__/topics/createTopic.test.ts
  back/src/__tests__/topics/getTopics.test.ts
  back/src/__tests__/topics/patchTopic.test.ts
  back/src/controllers/index.ts
  back/src/controllers/topics/create.ts
  back/src/controllers/topics/get.ts
  back/src/controllers/topics/patch.ts
  back/src/middleware/authMiddleware.ts
  back/src/routes/authRouter.ts
  back/src/routes/index.ts
  back/src/routes/mediaRouter.ts
  back/src/routes/resourcesRouter.ts
  back/src/routes/topics.ts
  back/src/routes/topicsRouter.ts
  back/src/routes/voteRouter.ts
  back/src/schemas/index.ts
  back/src/schemas/resource/resourceGetSchema.ts
  back/src/schemas/topic/topicCreateSchema.ts
  back/src/schemas/topic/topicPatchSchema.ts
  back/src/schemas/topic/topicSchema.ts
Labels: enhancement, backend

#414 add separated by concerns authenticate and authorize middleware
  back/src/__tests__/helpers/checkRoleAccess.test.ts
  back/src/helpers/checkRoleAccess.ts
  back/src/helpers/errors.ts
  back/src/helpers/index.ts
  back/src/middleware/authMiddleware.ts
  back/src/middleware/authenticate.ts
  back/src/middleware/authorize.ts
  back/src/middleware/index.ts
  back/src/routes/authRouter.ts
  back/src/routes/mediaRouter.ts
  back/src/routes/resourcesRouter.ts
  back/src/routes/topics.ts
  back/src/routes/voteRouter.ts
Labels: backend

#410 395 add tooltip component
  front/src/__tests__/molecules/Tooltip.test.tsx
  front/src/components/molecules/Tooltip.tsx
  front/src/components/molecules/index.ts
Labels: frontend

#411 376-fe-update-design-home-page
  front/src/__tests__/pages/Home.test.tsx
  front/src/assets/icons/bg-home-card-corner.svg
  front/src/assets/icons/new-folder-dynamic-color.svg
  front/src/assets/icons/puzzle-dynamic-color.svg
  front/src/components/molecules/CardHome.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/pages/Home.tsx
Labels: frontend

#413 412-fe-show-updated-date-on-cardresource
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/__tests__/molecules/CreateAuthor.test.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/CreateAuthor.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceCardList.tsx
Labels: bug, frontend

#397 [FE] Redesign navbar desktop and mobile
  front/src/__tests__/molecules/SelectLanguage.test.tsx
  front/src/__tests__/molecules/UserButton.test.tsx
  front/src/__tests__/organisms/CategoriesList.test.tsx
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/assets/icons/menu-left.svg
  front/src/assets/icons/plus.svg
  front/src/assets/icons/settings.svg
  front/src/assets/icons/user.svg
  front/src/assets/icons/x.svg
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/index.ts
  front/src/pages/Home.tsx
Labels: frontend

#417 416-be-modify-server-so-path-static-media-is-relative
  back/src/server.ts
Labels: backend

#432 429-be Upload userPatchSchema and openapi update
  back/src/openapi/routes/users/patch.ts
  back/src/schemas/index.ts
  back/src/schemas/resource/resourceGetSchema.ts
  back/src/schemas/users/userLoginSchema.ts
  back/src/schemas/users/userPatchSchema.ts
  back/src/schemas/users/userRegisterSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#433 403-fix-login-register-schemas
  packages/schemas/package-lock.json
  packages/schemas/package.json
  packages/schemas/src/Register.ts
Labels: frontend

#425 389 fe edit my resources
  front/src/__tests__/organisms/CardResource.test.tsx
  front/src/__tests__/organisms/CardResourceLink.test.tsx
  front/src/__tests__/organisms/EditResource.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CardResource.tsx
  front/src/components/organisms/CardResourceLink.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/index.ts
  front/src/pages/Category.tsx
Labels: frontend

#434 429 be create patch endpoint and controller for users
  back/openapi.yaml
  back/src/__tests__/users/patchUser.test.ts
  back/src/controllers/index.ts
  back/src/controllers/users/patch.ts
  back/src/middleware/errorMiddleware.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/users/patch.ts
  back/src/prisma/client.ts
  back/src/routes/users.ts
Labels: backend

#424 398 add spinner size as prop to spinner component
  front/src/__tests__/atoms/Spinner.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/atoms/Spinner.ts
  front/src/components/molecules/TypesFilterWidget.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/MyFavoritesList.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
Labels: enhancement, frontend

#409 408-updated layout and started tests
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/StatusFilterWidget.tsx
  front/src/components/molecules/TypesFilterWidget.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/ResourceCardList.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/components/organisms/index.ts
  front/src/helpers/fetchers.ts
  front/src/pages/Category.tsx
  front/src/pages/index.ts
  front/src/styles/dimensions.ts
Labels: frontend

#440 423-be-add-topics-patch-create-endpoints-to-openapi-swagger
  back/openapi.yaml
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/topics/create.ts
  back/src/openapi/routes/topics/get.ts
  back/src/openapi/routes/topics/patch.ts
  back/src/schemas/topic/topicPatchSchema.ts
  back/src/schemas/topic/topicSchema.ts
Labels: backend

#442 441-be-modify-validate-schemas-createdat-updatedat
  back/openapi.yaml
  back/src/__tests__/users/patchUser.test.ts
  back/src/schemas/users/userPatchSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#444 430-fe-create-tab-component
  front/src/__tests__/molecules/Tabs/TabItem.test.tsx
  front/src/__tests__/molecules/Tabs/Tabs.test.tsx
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/molecules/Tabs/TabItem.tsx
  front/src/components/molecules/Tabs/Tabs.tsx
  front/src/components/molecules/Tabs/index.ts
  front/src/components/molecules/index.ts
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/SettingsManager.tsx
  front/src/components/organisms/TopicsManager.tsx
  front/src/components/organisms/UsersManager.tsx
  front/src/components/organisms/index.ts
  front/src/main.tsx
Labels: frontend

#445 418 fe add users edit screen
  front/src/__tests__/pages/AccountAdmin.test.tsx
  front/src/constants/paths.ts
  front/src/main.tsx
  front/src/pages/AccountAdim.tsx
  front/src/pages/index.ts
Labels: frontend

#446 427 fe posicion botones overlay y transicion
  front/src/__tests__/atoms/HamburguerMenu.test.tsx
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/assets/icons/menu-left.svg
  front/src/assets/icons/plus.svg
  front/src/assets/icons/settings.svg
  front/src/assets/icons/x.svg
  front/src/components/atoms/HamburgerMenu.tsx
  front/src/components/atoms/index.ts
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/Navbar.tsx
Labels: frontend

#438 add fixed topics shape
  back/openapi.yaml
  back/src/__tests__/topics/getTopics.test.ts
  back/src/controllers/topics/get.ts
  back/src/openapi/components/responses/category.ts
  back/src/openapi/routes/topics/get.ts
Labels: backend

#405 373-update-validation-form
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/atoms/Input.test.tsx
  front/src/__tests__/atoms/Spinner.test.tsx
  front/src/__tests__/organisms/Login.test.tsx
  front/src/__tests__/organisms/Register.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/atoms/Button.tsx
  front/src/components/atoms/Input.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/atoms/Spinner.ts
  front/src/components/molecules/Modal.tsx
  front/src/components/organisms/Login.tsx
  front/src/components/organisms/Register.tsx
  front/src/constants/urls.ts
  front/src/helpers/fetchers.ts
  front/src/helpers/index.ts
  front/src/pages/AccountAdim.tsx
Labels: frontend

#452 447-FE-update-getTopics-to-map-from-array
  front/src/__mocks__/handlers.ts
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/helpers/fetchers.ts
  front/src/pages/Category.tsx
Labels: frontend

#450 399-add-transition-to-modals
  front/src/__tests__/molecules/Modal.test.tsx
  front/src/__tests__/pages/Category.test.tsx
  front/src/components/molecules/Modal.tsx
Labels: frontend

#449 402-be-add-pre-chosen-user-specialization
  back/openapi.yaml
  back/prisma/data/users.ts
  back/prisma/migrations/20230725105919_add_user_specialization/migration.sql
  back/prisma/migrations/20230725134336_make_slug_required_on_category/migration.sql
  back/prisma/schema.prisma
  back/prisma/seed.ts
  back/src/__tests__/auth/register.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/users/get.test.ts
  back/src/__tests__/users/patchUser.test.ts
  back/src/controllers/auth/registerController.ts
  back/src/schemas/users/userRegisterSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#456 426-febug-fix-home-category-jump
  front/src/__tests__/molecules/CategoryBlock.test.tsx
  front/src/__tests__/molecules/UserAccessHome.test.tsx
  front/src/__tests__/molecules/UserButton.test.tsx
  front/src/__tests__/organisms/DesktopSideMenu.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/molecules/CategoryBlock.tsx
  front/src/components/molecules/SelectGroup.tsx
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserAccessHome.tsx
  front/src/components/molecules/UserButton.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/DesktopSideMenu.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/index.ts
  front/src/pages/Category.tsx
  front/src/pages/Home.tsx
Labels: frontend

#462 459-be-migration-allowing-null-user-specialization
  back/openapi.yaml
  back/prisma/migrations/20230725105919_add_user_specialization/migration.sql
  back/prisma/migrations/20230725134336_make_slug_required_on_category/migration.sql
  back/prisma/migrations/20230727092732_add_user_specialization_nullable/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/auth/register.test.ts
  back/src/controllers/auth/registerController.ts
  back/src/schemas/users/userSchema.ts
Labels: backend

#463 [FE][BUG] update create resource to send id instead of slug #453
  front/src/__tests__/atoms/Select.test.tsx
  front/src/__tests__/organisms/Register.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/atoms/Select.tsx
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/Register.tsx
  front/src/components/organisms/ResourceForm.tsx
Labels: bug, frontend
