Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-09, with the labels that each got.

#464 415-fe-settings-modal-to-manage-topics
  front/src/__mocks__/handlers.ts
  front/src/__tests__/molecules/TopicsEditableItem.test.tsx
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  front/src/assets/icons/delete-icon.svg
  front/src/assets/icons/index.ts
  front/src/components/molecules/Modal.tsx
  front/src/components/molecules/Tabs/Tabs.tsx
  front/src/components/molecules/TopicsEditableItem.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/CategoriesList.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/SettingsManager.tsx
  front/src/components/organisms/TopicsManager.tsx
  front/src/components/organisms/TopicsManagerBoard.tsx
  front/src/components/organisms/index.ts
  front/src/helpers/fetchers.ts
Labels: frontend

#469 468-fe-fix-categories-design
  front/src/__mocks__/handlers.ts
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/helpers/fetchers.ts
  front/src/pages/Category.tsx
Labels: bug, frontend

#476 448-be-modify-registercontroller-so-duplicates-are-automatically-handled-by-errormiddleware
  back/openapi.yaml
  back/src/__tests__/auth/register.test.ts
  back/src/controllers/auth/register.ts
  back/src/controllers/index.ts
  back/src/helpers/errors.ts
  back/src/middleware/errorMiddleware.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/routes/auth/register.ts
Labels: enhancement, backend

#480 474-be-bug-registration-form
  back/openapi.yaml
  back/src/__tests__/auth/register.test.ts
  back/src/controllers/auth/register.ts
  back/src/schemas/users/userRegisterSchema.ts
Labels: bug, backend

#478 472-fe-hamburguer-menu-appears-on-mid-size-screen
  front/src/components/atoms/HamburgerMenu.tsx
Labels: bug, frontend

#477 451 add remove favourite resource by user endpoint
  .gitignore
  back/src/__tests__/favorites/putFavoriteByUserId.test.ts
  back/src/controllers/favorites/putFavoriteByUserId.ts
  back/src/controllers/index.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/routes/favorites/put.ts
  back/src/openapi/routes/index.ts
  back/src/routes/favorites.ts
  back/src/routes/index.ts
  back/src/routes/routes.ts
  back/src/schemas/favorites/favoritePutSchema.ts
  back/src/server.ts
Labels: backend

#482 473 fe register form is not sending correct data
  front/src/components/organisms/Register.tsx
Labels: bug, frontend

#471 added translation to front page
  front/package-lock.json
  front/package.json
  front/src/__tests__/molecules/SelectLanguage.test.tsx
  front/src/__tests__/molecules/UserAccessHome.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/__tests__/test-utils.tsx
  front/src/components/molecules/CardHome.tsx
  front/src/components/molecules/SelectLanguage.tsx
  front/src/components/molecules/UserAccessHome.tsx
  front/src/i18n.ts
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/main.tsx
  front/src/pages/Home.tsx
Labels: frontend

#491 490-readmemd-update
  README.md
Labels: documentation

#502 496-fe-update-copy-login-non-active-account
  front/src/components/organisms/Login.tsx
Labels: frontend

#503 407 fe create loginmodal and registermodal components
  front/src/__tests__/organisms/UserAccesHome.test.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/UserAccessHome.tsx
  front/src/components/organisms/index.ts
  front/src/pages/Home.tsx
Labels: frontend

#488 487-be-bug-fix-get-favorite-resources-by-user-endpoint
  back/openapi.yaml
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/resources/favorites.test.ts
  back/src/controllers/resources/getFavoriteResources.ts
  back/src/helpers/errors.ts
  back/src/middleware/errorMiddleware.ts
  back/src/openapi/routes/resources/favorites.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/index.ts
  back/src/schemas/resource/resourceFavoriteSchema.ts
Labels: bug, backend

#507 498 febug stay on the same page with modal open after submitting resources
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/organisms/MyResources.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/utils/navigation.tsx
Labels: bug, frontend

#483 344 create filters context
  front/src/__tests__/context/store/context.test.tsx
  front/src/__tests__/context/store/reducer.test.tsx
  front/src/context/store/context.tsx
  front/src/context/store/reducer.tsx
  front/src/context/store/types.tsx
  front/src/helpers/fetchers.ts
  front/src/main.tsx
Labels: frontend

#509 [FE] Status filters should only appear when user is logged-in
  front/src/pages/Category.tsx
Labels: frontend
