Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2023-05, with the labels that each got.

#201 190 be create new unique column slug on topics and resources
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/prisma/data/resources.ts
  back/prisma/data/topics.ts
  back/prisma/migrations/20230428085924_add_slug_columns/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/resources/resources.test.ts
  back/src/schemas/resourceCreateSchema.ts
  back/src/schemas/resourceSchema.ts
  back/src/schemas/topicSchema.ts
Labels: backend

#159 96 be create handler for get to resources with optional parameters of type and or topic
  back/openapi.yaml
  back/prisma/data/resources.ts
  back/prisma/migrations/20230430171259_topic_resource/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/resources/create.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/index.ts
  back/src/controllers/resourceController.ts
  back/src/controllers/resources/createResourceController.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/create.ts
  back/src/openapi/routes/resources/get.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/resourceCreateSchema.ts
  back/src/schemas/resourcesGetSchema.ts
Labels: backend

#206 202 select warning
  front/src/__tests__/atoms/Select.test.tsx
  front/src/components/atoms/Select.tsx
Labels: bug, frontend

#210 178 be vote counter put
  back/openapi.yaml
  back/src/__tests__/resources/vote.test.ts
  back/src/config/config.ts
  back/src/controllers/index.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/controllers/resources/voteController.ts
  back/src/helpers/errors.ts
  back/src/middleware/swaggeruiCSPMiddleware.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/get.ts
  back/src/openapi/routes/resources/vote.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/dniSchema.ts
  back/src/schemas/index.ts
  back/src/schemas/resource/resourceCreateSchema.ts
  back/src/schemas/resource/resourceGetSchema.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/schemas/resource/resourcesGetSchemaParams.ts
  back/src/schemas/resourceSchema.ts
  back/src/schemas/topicSchema.ts
  back/src/schemas/userSchema.ts
Labels: backend

#193 182-fe-create-author-molecule
  front/src/__tests__/molecules/AvatarInfo.test.tsx
  front/src/__tests__/molecules/CreateAuthor.test.tsx
  front/src/components/molecules/AvatarInfo.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/CardResourceHome.tsx
  front/src/components/molecules/CreateAuthor.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/ResourcesList.tsx
  front/src/pages/Home.tsx
Labels: frontend

#211 139 create link component
  front/package-lock.json
  front/package.json
  front/src/__tests__/atoms/Link.test.tsx
  front/src/components/atoms/Link.tsx
  front/src/components/atoms/index.ts
  front/src/styles/font.ts
Labels: frontend

#215 172 be documentar post resources
  back/openapi.yaml
  back/src/__tests__/resources/create.test.ts
  back/src/controllers/resources/createResourceController.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/create.ts
  back/src/openapi/routes/resources/get.ts
  back/src/openapi/routes/resources/me.ts
  back/src/schemas/resource/resourceCreateSchema.ts
Labels: backend

#216 171-document-topics-endpoints
  back/openapi.yaml
  back/src/__tests__/topics/topics.test.ts
  back/src/controllers/topicController.ts
  back/src/openapi/routes/topics/category.ts
  back/src/openapi/routes/topics/topics.ts
  back/src/schemas/topicSchema.ts
Labels: documentation, backend

#217 179 get votes (controller, test, swagger)
  back/openapi.yaml
  back/src/__tests__/resources/vote.test.ts
  back/src/__tests__/setup.ts
  back/src/controllers/index.ts
  back/src/controllers/resources/voteController.ts
  back/src/openapi/routes/resources/vote.ts
  back/src/routes/resourcesRouter.ts
Labels: backend

#222 184 recover categories from the be
  front/package-lock.json
  front/package.json
  front/src/__tests__/organisms/CategoriesList.test.tsx
  front/src/assets/icons/index.ts
  front/src/assets/icons/java.svg
  front/src/assets/icons/nodejs-logo.svg
  front/src/assets/icons/php.svg
  front/src/components/organisms/CategoriesList.tsx
  front/src/main.tsx
  front/src/pages/Home.tsx
Labels: frontend

#229 adjust my resources and favorites spacing
  front/src/pages/Home.tsx
Labels: frontend

#231 176-fe-create-resource-card
  front/index.html
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/CardResourceHome.tsx
  front/src/components/molecules/CreateAuthor.tsx
  front/src/components/molecules/ResourceTitleLink.tsx
  front/src/components/molecules/index.ts
  front/src/components/organisms/ResourcesList.tsx
  front/src/pages/Home.tsx
  front/src/styles/font.ts
Labels: frontend

#213 177 vote counter
  back/package-lock.json
  front/package-lock.json
  front/sonar-project.properties
  front/src/__mocks__/handlers.ts
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/molecules/index.ts
  front/src/constants/urls.ts
  front/src/pages/Home.tsx
  front/src/pages/Resource.tsx
Labels: frontend

#236 Add vote counter to ResourceCard and fix Resource
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/__tests__/molecules/VoteCounter.test.tsx
  front/src/__tests__/pages/Resource.test.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/VoteCounter.tsx
  front/src/components/organisms/ResourcesList.tsx
  front/src/pages/Home.tsx
  front/src/pages/Resource.tsx
Labels: frontend

#240 223 be handle media upload of files
  back/.gitignore
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/src/__tests__/media/media.test.ts
  back/src/controllers/index.ts
  back/src/controllers/media/postMediaController.ts
  back/src/middleware/authMiddleware.ts
  back/src/middleware/index.ts
  back/src/middleware/uploadImageMiddleware.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/media.ts
  back/src/routes/index.ts
  back/src/routes/mediaRouter.ts
  back/src/routes/routes.ts
  back/src/server.ts
Labels: backend

#220 189-fe-search-resources-by-title
  front/src/__tests__/hooks/useSearch.test.tsx
  front/src/__tests__/molecules/CardResource.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/components/atoms/Icon.tsx
  front/src/components/atoms/Input.tsx
  front/src/components/molecules/CardResource.tsx
  front/src/components/molecules/InputGroup.tsx
  front/src/components/organisms/ResourcesList.tsx
  front/src/hooks/index.ts
  front/src/hooks/useSearch.tsx
  front/src/pages/Home.tsx
  front/src/pages/Resource.tsx
  front/src/styles/mediaQueries.ts
Labels: frontend

#239 00-update readme with AuthProvider
  README.md
  front/README.md
Labels: documentation

#247 243 be get topics by slug category
  back/openapi.yaml
  back/src/__tests__/topics/topics.test.ts
  back/src/controllers/index.ts
  back/src/controllers/topicController.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/topics/category.ts
  back/src/openapi/routes/topics/topics.ts
  back/src/routes/topicsRouter.ts
  back/src/schemas/topicSchema.ts
Labels: backend

#244 226 auth provider use get me endpoint
  front/src/__mocks__/handlers.ts
  front/src/__tests__/context/AuthProvider.test.tsx
  front/src/constants/urls.ts
  front/src/context/AuthProvider.tsx
Labels: frontend

#254 fixed swagger docs
  back/openapi.yaml
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/topic.ts
Labels: bug, backend

#246 238-home homeCard and their tests
  back/openapi.yaml
  front/src/__tests__/molecules/CardHome.test.tsx
  front/src/__tests__/pages/Home.test.tsx
  front/src/assets/icons/eCopia_Certificat_desplacament_temporal_RTC007TEMP1684309976268.pdf
  front/src/assets/icons/index.ts
  front/src/assets/icons/puzzle-dynamic-color.svg
  front/src/assets/icons/thumb-up-dynamic-color.svg
  front/src/components/molecules/CardHome.tsx
  front/src/components/molecules/index.ts
  front/src/pages/Home.tsx
Labels: frontend

#260 233 be regorganize vote endpoint putget
  back/openapi.yaml
  back/src/__tests__/resources/vote.test.ts
  back/src/__tests__/vote/vote.test.ts
  back/src/controllers/index.ts
  back/src/controllers/vote/voteController.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/vote/vote.ts
  back/src/routes/index.ts
  back/src/routes/resourcesRouter.ts
  back/src/routes/routes.ts
  back/src/routes/voteRouter.ts
  back/src/schemas/index.ts
  back/src/schemas/voteCountSchema.ts
  back/src/server.ts
Labels: backend

#234 173 get user favorite resources
  back/openapi.yaml
  back/prisma/seed.ts
  back/src/__tests__/favorites/favorites.test.ts
  back/src/controllers/favoriteController.ts
  back/src/controllers/index.ts
  back/src/openapi/routes/favorites.ts
  back/src/openapi/routes/index.ts
  back/src/routes/favoritesRouter.ts
  back/src/routes/index.ts
  back/src/routes/routes.ts
  back/src/server.ts
Labels: backend

#261 52 create navbar
  front/package-lock.json
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/index.ts
Labels: frontend

#266 262 be resource getters return vote info
  back/openapi.yaml
  back/src/__tests__/resources/byTopic.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/resources/me.test.ts
  back/src/__tests__/vote/vote.test.ts
  back/src/controllers/resources/getResourcesByTopic.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/helpers/addVoteCountToResource.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/authMiddleware.ts
  back/src/openapi/routes/favorites.ts
  back/src/openapi/routes/resources/me.ts
  back/src/schemas/resource/resourceCreateSchema.ts
  back/src/schemas/resource/resourceGetSchema.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/schemas/topicSchema.ts
Labels: backend

#269 New Category logos added
  front/src/assets/icons/data-science.svg
  front/src/assets/icons/eCopia_Certificat_desplacament_temporal_RTC007TEMP1684309976268.pdf
  front/src/assets/icons/index.ts
  front/src/assets/icons/python.svg
  front/src/assets/icons/spring.svg
  front/src/components/organisms/CategoriesList.tsx
Labels: frontend

#268 265 fe add navbar to categories page
  front/src/__tests__/organisms/Navbar.test.tsx
  front/src/__tests__/pages/Resource.test.tsx
  front/src/__tests__/test-utils.tsx
  front/src/components/organisms/Navbar.tsx
  front/src/context/AuthProvider.tsx
  front/src/pages/Resource.tsx
Labels: frontend

#271 263 add logo to home
  front/src/assets/icons/index.ts
  front/src/assets/icons/it-logo.svg
  front/src/pages/Home.tsx
Labels: frontend

#275 245 be get resource by id
  back/openapi.yaml
  back/package.json
  back/src/__tests__/favorites/favorites.test.ts
  back/src/__tests__/mocks/resources.ts
  back/src/__tests__/resources/byId.test.ts
  back/src/__tests__/resources/byTopic.test.ts
  back/src/__tests__/resources/get.test.ts
  back/src/__tests__/resources/me.test.ts
  back/src/controllers/index.ts
  back/src/controllers/resources/getResourcesById.ts
  back/src/controllers/resources/getResourcesByTopic.ts
  back/src/controllers/resources/getResourcesByUserId.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/helpers/addVoteCountToResource.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/resources/id.ts
  back/src/routes/resourcesRouter.ts
Labels: backend

#280 272 be add category slug to get resources
  back/openapi.yaml
  back/src/__tests__/resources/get.test.ts
  back/src/controllers/resources/getResourcesController.ts
  back/src/controllers/topicController.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/authMiddleware.ts
  back/src/openapi/routes/auth/login.ts
  back/src/openapi/routes/auth/me.ts
  back/src/openapi/routes/resources/get.ts
  back/src/openapi/routes/resources/id.ts
  back/src/openapi/routes/resources/topic.ts
  back/src/openapi/routes/topics/topics.ts
  back/src/routes/resourcesRouter.ts
  back/src/schemas/index.ts
  back/src/schemas/resource/resourcesGetParamsSchema.ts
Labels: backend
