Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-02, with the labels that each got.

#900 fe-removed-avatar-error-from-stories
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/stories/atoms/avatar/index.stories.tsx
Labels: enhancement, frontend

#909 856-fe-implement-tabs-with-UI-component-in-ita-wiki
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/molecules/Tabs/TabItem.test.tsx
  front/src/__tests__/molecules/Tabs/Tabs.test.tsx
  front/src/components/molecules/Tabs/TabItem.tsx
  front/src/components/molecules/Tabs/Tabs.tsx
  front/src/components/molecules/Tabs/index.ts
  front/src/components/organisms/SettingsManager.tsx
Labels: frontend

#929 754-fe-migrate-select-component-to-storybook
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Select.test.tsx
  packages/ui/src/components/atoms/Select.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Select.stories.ts
Labels: frontend

#921 920 Migrate AccessModalContent to package UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/AccessModalContent.test.tsx
  packages/ui/src/components/molecules/AccessModalContent.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/AccessModalContent/index.stories.ts
  packages/ui/src/stories/molecules/AccessModalContent/lock-dynamic-color.svg
Labels: enhancement, frontend

#903 901-fe-migrate-textarea-to-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Textarea.test.tsx
  packages/ui/src/components/atoms/Avatar/index.tsx
  packages/ui/src/components/atoms/Button.tsx
  packages/ui/src/components/atoms/Checkbox.tsx
  packages/ui/src/components/atoms/Counter.tsx
  packages/ui/src/components/atoms/HamburgerMenu.tsx
  packages/ui/src/components/atoms/Icon.tsx
  packages/ui/src/components/atoms/Input.tsx
  packages/ui/src/components/atoms/Label.tsx
  packages/ui/src/components/atoms/Radio.tsx
  packages/ui/src/components/atoms/Select.tsx
  packages/ui/src/components/atoms/Spinner.ts
  packages/ui/src/components/atoms/Text.ts
  packages/ui/src/components/atoms/Textarea.tsx
  packages/ui/src/components/atoms/Title.ts
  packages/ui/src/components/atoms/ValidationMessage.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/components/molecules/AccessModalContent.tsx
  packages/ui/src/components/molecules/BackButton.tsx
  packages/ui/src/components/molecules/InputGroup.tsx
  packages/ui/src/components/molecules/Modal.tsx
  packages/ui/src/components/molecules/Tabs/TabItem.tsx
  packages/ui/src/components/molecules/Tabs/Tabs.tsx
  packages/ui/src/components/molecules/Tabs/index.ts
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/atoms/Button.stories.ts
  packages/ui/src/stories/atoms/Counter.stories.ts
  packages/ui/src/stories/atoms/HamburgerMenu.stories.ts
  packages/ui/src/stories/atoms/Icon.stories.ts
  packages/ui/src/stories/atoms/Input.stories.ts
  packages/ui/src/stories/atoms/Label.stories.ts
  packages/ui/src/stories/atoms/Radio.stories.ts
  packages/ui/src/stories/atoms/Spinner.stories.ts
  packages/ui/src/stories/atoms/Text.stories.ts
  packages/ui/src/stories/atoms/Textarea.stories.tsx
  packages/ui/src/stories/atoms/Title.stories.ts
  packages/ui/src/stories/atoms/ValidationMessage.stories.ts
  packages/ui/src/stories/molecules/AccessModalContent/index.stories.ts
  packages/ui/src/stories/molecules/BackButton.stories.ts
  packages/ui/src/stories/molecules/InputGroup.stories.ts
  packages/ui/src/stories/molecules/Modal.stories.tsx
  packages/ui/src/stories/molecules/Tabs/Tabs.stories.tsx
  packages/ui/src/styles/index.ts
Labels: enhancement, frontend

#927 926-fe-fix-remove-unnecessary-props-from-component-NavBar-with-shouldforwardprops
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/components/organisms/Navbar.tsx
  front/src/components/organisms/Search.tsx
  front/src/styles/FlexBox.ts
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: bug, enhancement, frontend

#941 863 fe implement radio component from UI into ita wiki
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/atoms/Radio.test.tsx
  front/src/__tests__/organisms/ResourceForm.test.tsx
  front/src/components/atoms/Radio.tsx
  front/src/components/atoms/index.ts
  front/src/components/organisms/EditResource.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/components/organisms/index.ts
Labels: frontend

#944 938-fe-migrate-selectgroup-to-package-UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/SelectGroup.test.tsx
  packages/ui/src/components/molecules/SelectGroup.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/SelectGroup.stories.tsx
Labels: frontend, ui

#940 931 migrate cardprofile to ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/CardProfile.test.tsx
  packages/ui/src/components/molecules/CardProfile.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/cardprofile/index.stories.ts
  packages/ui/src/stories/molecules/cardprofile/logout.svg
  packages/ui/src/stories/molecules/cardprofile/profile-avatar.svg
Labels: enhancement, frontend

#930 928-fe-migrate-createauthor-to-package-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/CreateAuthor.test.tsx
  packages/ui/src/components/molecules/CreateAuthor.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/CreateAuthor.stories.ts
Labels: enhancement, frontend

#958 fe sso add basic layout
  sso_front/CHANGELOG.md
  sso_front/package.json
  sso_front/src/__tests__/main.test.tsx
  sso_front/src/__tests__/organisms/Navbar.test.tsx
  sso_front/src/__tests__/organisms/SideMenu.test.tsx
  sso_front/src/__tests__/pages/Home.test.tsx
  sso_front/src/assets/.gitkeep
  sso_front/src/assets/icons/index.ts
  sso_front/src/assets/icons/it-logo.svg
  sso_front/src/assets/icons/user.svg
  sso_front/src/components/organisms/Navbar.tsx
  sso_front/src/components/organisms/SideMenu.tsx
  sso_front/src/components/organisms/index.ts
  sso_front/src/pages/Home.tsx
Labels: frontend

#956 951-fe-migrate-filter-widget-to-package-UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/CheckboxFilterWidget.test.tsx
  packages/ui/src/components/molecules/CheckboxFilterWidget.tsx
  packages/ui/src/components/molecules/SelectGroup.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/CheckboxFilterWidget.stories.tsx
Labels: frontend, ui

#954 933 migrate cardhome to package ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/CardHome.test.tsx
  packages/ui/src/components/molecules/CardHome.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/cardhome/bg-home-card-corner.svg
  packages/ui/src/stories/molecules/cardhome/index.stories.ts
  packages/ui/src/stories/molecules/cardhome/puzzle-dynamic-color.svg
Labels: enhancement, frontend

#970 fe-migrate-resourcetitlelink-to-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/ResourceTitleLink.test.tsx
  packages/ui/src/components/molecules/ResourceTitleLink.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/ResourceTitleLink.stories.ts
Labels: enhancement, frontend, ui

#971 961-fe-migrate-topics-editable-item-to-package-UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/EditableItem.test.tsx
  packages/ui/src/components/molecules/EditableItem.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/editableItem/delete-icon.svg
  packages/ui/src/stories/molecules/editableItem/index.stories.tsx
Labels: frontend, ui

#975 892-be-sso-implement-admin-only-login-endpoint
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/dashboard/auth/login.test.ts
  sso/src/__tests__/dashboard/auth/logout.test.ts
  sso/src/app.ts
  sso/src/controllers/dashboard/auth/login.ts
  sso/src/controllers/dashboard/auth/logout.ts
  sso/src/openapi/components/setCookieHeader.ts
  sso/src/openapi/config.ts
  sso/src/openapi/routes/dashboard/auth/login.ts
  sso/src/openapi/routes/dashboard/auth/logout.ts
  sso/src/openapi/routes/index.ts
  sso/src/routes/dashboard/authRoutes.ts
  sso/src/routes/index.ts
  sso/src/routes/routes.ts
Labels: enhancement, backend

#972 968 fe migrate textareagroup to UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/TextareaGroup.test.tsx
  packages/ui/src/components/molecules/TextareaGroup.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/TextareaGroup.stories.ts
Labels: enhancement, frontend

#983 980-be-sso-implement-admin-only-get-users-endpoint-with-id-name-itinerary-status-and-signup-date
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/dashboard/auth/logout.test.ts
  sso/src/__tests__/dashboard/users/list.test.ts
  sso/src/__tests__/users/list.test.ts
  sso/src/app.ts
  sso/src/controllers/dashboard/users/list.ts
  sso/src/controllers/users/list.ts
  sso/src/middleware/authenticate.ts
  sso/src/middleware/authorize.ts
  sso/src/openapi/components/cookieAuth.ts
  sso/src/openapi/components/responses.ts
  sso/src/openapi/config.ts
  sso/src/openapi/routes/dashboard/users/list.ts
  sso/src/openapi/routes/index.ts
  sso/src/openapi/routes/users/list.ts
  sso/src/routes/dashboard/usersRoutes.ts
  sso/src/routes/index.ts
  sso/src/routes/routes.ts
  sso/src/routes/usersRoutes.ts
  sso/src/schemas/index.ts
  sso/src/schemas/itineraries/itinerarySchema.ts
  sso/src/schemas/users/dashboardUsersListSchema.ts
Labels: enhancement, backend

#989 981-fe-refactor-avatar-props
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Avatar.test.tsx
  packages/ui/src/components/atoms/Avatar/default.svg
  packages/ui/src/components/atoms/Avatar/index.tsx
  packages/ui/src/stories/atoms/avatar/index.stories.tsx
Labels: enhancement, frontend

#995 988-be-sso-implement-itinerary-slug-filter-to-get-users
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/dashboard/users/list.test.ts
  sso/src/controllers/dashboard/users/list.ts
  sso/src/openapi/config.ts
  sso/src/openapi/routes/dashboard/users/list.ts
  sso/src/routes/dashboard/usersRoutes.ts
  sso/src/schemas/index.ts
  sso/src/schemas/itineraries/itinerarySchema.ts
  sso/src/schemas/users/dashboardUsersListQuerySchema.ts
  sso/src/schemas/users/dashboardUsersListSchema.ts
Labels: enhancement, backend

#993 880 fe sso add date filter component
  sso_front/CHANGELOG.md
  sso_front/package-lock.json
  sso_front/package.json
  sso_front/src/__tests__/molecules/DateRange.test.tsx
  sso_front/src/__tests__/organisms/FiltersWidget.test.tsx
  sso_front/src/assets/icons/calendar.svg
  sso_front/src/assets/icons/index.ts
  sso_front/src/components/layout/index.ts
  sso_front/src/components/molecules/DateRange.tsx
  sso_front/src/components/molecules/index.ts
  sso_front/src/components/organisms/FiltersWidget.tsx
  sso_front/src/components/organisms/index.ts
  sso_front/src/locales/cat.json
  sso_front/src/locales/en.json
  sso_front/src/locales/es.json
  sso_front/src/main.tsx
  sso_front/src/pages/Home.tsx
  sso_front/src/pages/index.ts
Labels: frontend

#997 974-fe-migrate-tooltip-to-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/Tooltip.test.tsx
  packages/ui/src/components/molecules/Tooltip.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/Tooltip.stories.tsx
Labels: frontend, ui

#999 998-be-sso-implement-status-filter-for-get-users
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/dashboard/users/list.test.ts
  sso/src/controllers/dashboard/users/list.ts
  sso/src/openapi/config.ts
  sso/src/schemas/users/dashboardUsersListQuerySchema.ts
  sso/src/schemas/users/dashboardUsersListSchema.ts
  sso/src/schemas/users/userSchema.ts
Labels: enhancement, backend

#987 984 fe migrate votecounter to UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/VoteCounter.test.tsx
  packages/ui/src/components/molecules/VoteCounter.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/VoteCounter.stories.tsx
Labels: enhancement, frontend

#991 990-fe-refactor-icon-props-with-favorites-icon
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Icon.test.tsx
  packages/ui/src/components/atoms/Icon.tsx
  packages/ui/src/stories/atoms/Icon.stories.ts
Labels: enhancement, frontend

#1014 1013-fe-ui-bug-fix-bug-in-checkbox-filter-widgets-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/molecules/CheckboxFilterWidget.tsx
Labels: bug, frontend, ui

#1015 1005-be-sso-implement-date-range-filtering-for-get-users
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package.json
  sso/src/__tests__/dashboard/users/list.test.ts
  sso/src/controllers/dashboard/users/list.ts
  sso/src/openapi/config.ts
  sso/src/schemas/users/dashboardUsersListQuerySchema.ts
Labels: enhancement, backend

#964 908-fe-migrate-dropdown-to-ui
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Dropdown.stories.tsx
Labels: enhancement, frontend
