Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-06, with the labels that each got.

#1312 Improve Banner molecule
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/Banner.test.tsx
  packages/ui/src/components/molecules/Banner/index.tsx
  packages/ui/src/stories/molecules/Banner.stories.ts
Labels: frontend, ui

#1317 1302-bewiki-remove-banner-entityendpoint
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/prisma/migrations/20240530113837_remove_banners/migration.sql
  services/wiki/prisma/schema.prisma
  services/wiki/prisma/seed.ts
  services/wiki/src/__tests__/banners/list.test.ts
  services/wiki/src/controllers/banners/list.ts
  services/wiki/src/controllers/index.ts
  services/wiki/src/openapi/routes/banners/list.ts
  services/wiki/src/openapi/routes/index.ts
  services/wiki/src/routes/banners.ts
  services/wiki/src/routes/index.ts
  services/wiki/src/routes/routes.ts
  services/wiki/src/server.ts
Labels: backend

#1318 1314-be-sso-allow-mentor-role-login-on-dashboardlogin-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/auth/login.test.ts
  services/sso/src/controllers/dashboard/auth/login.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1321 1319-feui-create-radiogroup-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/RadioGroup.test.tsx
  packages/ui/src/components/molecules/RadioGroup.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/RadioGroup.stories.ts
Labels: frontend, ui

#1330 1325-be-sso-return-only-the-itinerary-data-specific-to-the-logged-in-mentor
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/unit/utils/queryBuilder.test.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/openapi/config.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
  services/sso/src/utils/queryBuilder.ts
Labels: enhancement, backend

#1313 1299-fewikibug-required-radio-buttons-error-message
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/ResourceForm.test.tsx
  web/wiki/src/components/organisms/ResourceForm.tsx
  web/wiki/src/locales/cat.json
  web/wiki/src/locales/en.json
  web/wiki/src/locales/es.json
Labels: bug, frontend

#1334 1248-feuiadd-disabled-property-to-button-to-pass-as-prop-in-dropdown-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
  packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
Labels: frontend, ui

#1338 1336-feusuaris-change-disabled-styles-in-dropdowns-with-disabled-prop-from-ui-component
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__tests__/molecules/ActionsDropdown.test.tsx
  web/usuaris/src/components/molecules/ActionsDropdown.tsx
  web/usuaris/src/components/molecules/RoleFilter.tsx
Labels: frontend

#1333 1309-feusuaris-display-sidemenu-options-according-to-user-role
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__tests__/organisms/SideMenu.test.tsx
  web/usuaris/src/components/organisms/SideMenu.tsx
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/menu.ts
  web/usuaris/src/context/AuthProvider.tsx
  web/usuaris/src/helpers/filters.ts
Labels: frontend

#1346 1345-feusuaris-fix-styles-to-hide-side-white-sections-and-match-ita-wiki-layout
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/components/organisms/Dashboard.tsx
  web/usuaris/src/components/organisms/SideMenu.tsx
  web/usuaris/src/main.tsx
  web/usuaris/src/pages/Home.tsx
Labels: bug, frontend

#1342 1301-fewikibug-create-resource-manage-error
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__mocks__/handlers.ts
  web/wiki/src/__tests__/hooks/useCreateResource.test.tsx
  web/wiki/src/__tests__/hooks/useUpdateResource.test.tsx
  web/wiki/src/__tests__/organisms/ResourceForm.test.tsx
  web/wiki/src/components/organisms/EditResource.tsx
  web/wiki/src/components/organisms/ResourceForm.tsx
  web/wiki/src/helpers/fetchers.ts
  web/wiki/src/locales/cat.json
  web/wiki/src/locales/en.json
  web/wiki/src/locales/es.json
Labels: bug, frontend

#1358 1344-besso-post-dashboardusersstatus-endpoint-must-permit-access-for-mentor-role-users
  services/sso/CHANGELOG.md
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/updateStatus.test.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
Labels: backend

#1361 1339-be-sso-restrict-mentor-role-to-patch-only-users-of-same-itinerary-and-prevent-role-field-modification
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/update.test.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/middleware/restrictMentorPatch.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/dashboard/users/update.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
Labels: enhancement, backend

#1360 1198-feui-pass-delay-value-for-debounce-as-props-in-search-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/Search/Search.test.tsx
  packages/ui/src/components/molecules/Search/Search.tsx
  packages/ui/src/stories/molecules/Search/Search.stories.ts
Labels: frontend, ui

#1343 1337-feusuaris-disable-role-itinerary-and-delete-option-for-mentor-users
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__tests__/molecules/ActionsDropdown.test.tsx
  web/usuaris/src/__tests__/molecules/ItineraryDropdown.test.tsx
  web/usuaris/src/__tests__/molecules/RoleFilter.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/ActionsDropdown.tsx
  web/usuaris/src/components/molecules/ItineraryDropdown.tsx
  web/usuaris/src/components/molecules/RoleFilter.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.styles.ts
  web/usuaris/src/components/organisms/UsersTable/index.tsx
Labels: frontend

#1365 1364-be-sso-fix-restrict-mentor-role-and-status-changes-allow-updates-to-registered-users-only
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/update.test.ts
  services/sso/src/middleware/restrictMentorPatch.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/dashboard/users/update.ts
Labels: bug, backend

#1370 1367-feui-add-disabled-prop-in-votecounter-and-storybook
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/VoteCounter.test.tsx
  packages/ui/src/components/molecules/VoteCounter.tsx
  packages/ui/src/stories/molecules/VoteCounter.stories.tsx
Labels: frontend

#1378 1308 fixed backgroundImg of CardHome
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/components/molecules/CardHome.tsx
Labels: bug, frontend

#1373 1304-bewiki-remove-avatar-upload-middleware-from-wiki
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/prisma/migrations/20240624222545_remove_upload_middlware_and_avatar/migration.sql
  services/wiki/prisma/schema.prisma
  services/wiki/src/__tests__/auth/me.test.ts
  services/wiki/src/__tests__/globalSetup.ts
  services/wiki/src/__tests__/media/media.test.ts
  services/wiki/src/__tests__/mocks/ssoHandlers/updateUserHandler.ts
  services/wiki/src/__tests__/resources/favorites.test.ts
  services/wiki/src/controllers/auth/authMeController.ts
  services/wiki/src/controllers/auth/register.ts
  services/wiki/src/controllers/index.ts
  services/wiki/src/controllers/media/postMediaController.ts
  services/wiki/src/controllers/resources/getFavoriteResources.ts
  services/wiki/src/controllers/users/patch.ts
  services/wiki/src/helpers/attachUserNamesToResources.ts
  services/wiki/src/helpers/processMedia.ts
  services/wiki/src/middleware/index.ts
  services/wiki/src/middleware/uploadImageMiddleware.ts
  services/wiki/src/routes/index.ts
  services/wiki/src/routes/mediaRouter.ts
  services/wiki/src/schemas/resource/resourceFavoriteSchema.ts
  services/wiki/src/schemas/users/userGetSchema.ts
  services/wiki/src/schemas/users/userPatchSchema.ts
  services/wiki/src/schemas/users/userSchema.ts
  services/wiki/src/server.ts
Labels: backend

#1376 729 vote race condition
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/CardResource.test.tsx
  web/wiki/src/components/organisms/CardResource.tsx
Labels: bug, frontend

#1388 1386-fewikiupdate-dependeces-from-itacademyui-to-fix-backgroundimg-bug
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
Labels: bug, frontend

#1383 1092-be-wiki-refactor-get-resources-to-omit-empty-username-fields-and…
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/resources/favorites.test.ts
  services/wiki/src/__tests__/resources/me.test.ts
  services/wiki/src/controllers/resources/getFavoriteResources.ts
  services/wiki/src/controllers/resources/getResourcesByUserId.ts
  services/wiki/src/helpers/attachUserNamesToResources.ts
  services/wiki/src/helpers/markFavorites.ts
  services/wiki/src/openapi/config.ts
  services/wiki/src/schemas/resource/resourceFavoriteSchema.ts
  services/wiki/src/schemas/resource/resourceGetSchema.ts
  services/wiki/src/schemas/resource/resourceSchema.ts
Labels: enhancement, backend
