Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-03, with the labels that each got.

#1023 1022-fe-sso-fix-console-error-in-layout-with-shouldforwardprop
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/components/layout/Layout.tsx
Labels: frontend

#1021 882-fe-sso-create-table
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__mocks__/server.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/main.test.tsx
  web/usuaris/src/__tests__/molecules/Table.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/__tests__/pages/Home.test.tsx
  web/usuaris/src/__tests__/setup.ts
  web/usuaris/src/assets/icons/index.ts
  web/usuaris/src/assets/icons/sort-down.svg
  web/usuaris/src/components/molecules/Table.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/UsersTable.tsx
  web/usuaris/src/components/organisms/index.ts
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/helpers/.gitkeep
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/.gitkeep
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useGetUsers.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/main.tsx
  web/usuaris/src/pages/Home.tsx
  web/usuaris/src/types/.gitkeep
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1045 1044-fe-bug-fix-inputgroup-and-icon-bug-in-packagesui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Icon.test.tsx
  packages/ui/src/__tests__/molecules/InputGroup.test.tsx
  packages/ui/src/components/atoms/Icon.tsx
  packages/ui/src/components/molecules/InputGroup.tsx
Labels: bug, frontend

#1051 1041-be-sso-add-letter-validation-for-dni-field
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/auth/register.test.ts
  services/sso/src/__tests__/dashboard/auth/login.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/openapi/config.ts
  services/sso/src/schemas/dniSchema.ts
  services/sso/src/utils/isValidDNILetter.ts
Labels: bug, backend

#1043 broken link fixed
  README.md
Labels: bug, documentation

#1049 1033-fewiki-fix-search-resource
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/components/organisms/Search.tsx
Labels: bug, frontend

#1050 1046-fe-packages-ui-fix-missing-avatar-in-cardprofile-molecule
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/CardProfile.test.tsx
  packages/ui/src/components/atoms/Avatar/index.tsx
  packages/ui/src/components/molecules/CardProfile.tsx
  packages/ui/src/stories/molecules/cardprofile/index.stories.ts
  packages/ui/src/stories/molecules/cardprofile/logout.svg
Labels: bug, frontend, ui

#1067 1027-fe-wiki-remove-atoms-replace-with-packagesui
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/atoms/BackButton.test.tsx
  web/wiki/src/__tests__/atoms/CheckBox.test.tsx
  web/wiki/src/__tests__/atoms/Counter.test.tsx
  web/wiki/src/__tests__/atoms/Dropdown.test.tsx
  web/wiki/src/__tests__/atoms/HamburguerMenu.test.tsx
  web/wiki/src/__tests__/atoms/Icon.test.tsx
  web/wiki/src/__tests__/atoms/Input.test.tsx
  web/wiki/src/__tests__/atoms/Label.test.tsx
  web/wiki/src/__tests__/atoms/Select.test.tsx
  web/wiki/src/__tests__/atoms/Spinner.test.tsx
  web/wiki/src/__tests__/atoms/Text.test.tsx
  web/wiki/src/__tests__/atoms/Textarea.test.tsx
  web/wiki/src/__tests__/atoms/Title.test.tsx
  web/wiki/src/__tests__/atoms/UserImage.test.tsx
  web/wiki/src/__tests__/atoms/ValidationMessage.test.tsx
  web/wiki/src/__tests__/styles/FlexBox.test.tsx
  web/wiki/src/__tests__/styles/dimensions.test.ts
  web/wiki/src/components/atoms/BackButton.tsx
  web/wiki/src/components/atoms/CheckBox.tsx
  web/wiki/src/components/atoms/Counter.tsx
  web/wiki/src/components/atoms/Dropdown.tsx
  web/wiki/src/components/atoms/HamburgerMenu.tsx
  web/wiki/src/components/atoms/Icon.tsx
  web/wiki/src/components/atoms/Input.tsx
  web/wiki/src/components/atoms/Label.tsx
  web/wiki/src/components/atoms/Select.tsx
  web/wiki/src/components/atoms/Spinner.ts
  web/wiki/src/components/atoms/Text.ts
  web/wiki/src/components/atoms/Textarea.tsx
  web/wiki/src/components/atoms/Title.ts
  web/wiki/src/components/atoms/UserImage.tsx
  web/wiki/src/components/atoms/ValidationMessage.tsx
  web/wiki/src/components/atoms/index.ts
  web/wiki/src/components/layout/Body.tsx
  web/wiki/src/components/molecules/TopicsEditableItem.tsx
  web/wiki/src/main.tsx
  web/wiki/src/pages/Category.tsx
  web/wiki/src/pages/ErrorPage.tsx
  web/wiki/src/pages/Home.tsx
  web/wiki/src/pages/Information.tsx
  web/wiki/src/styles/FlexBox.ts
  web/wiki/src/styles/colors.ts
  web/wiki/src/styles/dimensions.ts
  web/wiki/src/styles/font.ts
  web/wiki/src/styles/index.ts
  web/wiki/src/styles/mediaQueries.ts
Labels: frontend

#1056 1030-fe-SideMenu links, with hover and active state added + component code refactored
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__tests__/organisms/SideMenu.test.tsx
  web/usuaris/src/assets/icons/index.ts
  web/usuaris/src/assets/icons/user.svg
  web/usuaris/src/components/organisms/SideMenu.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
Labels: frontend

#1072 1071-be-wiki-handle-missing-user-names-without-throwing-servicefail
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/mocks/ssoHandlers/listUsersHandler.ts
  services/wiki/src/__tests__/resources/get.test.ts
  services/wiki/src/helpers/attachUserNamesToResources.ts
  services/wiki/src/openapi/config.ts
Labels: bug, backend

#1042 891 be sso implement blocked user status functionality
  services/sso/CHANGELOG.md
  services/sso/db/init.sql
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/auth/register.test.ts
  services/sso/src/__tests__/dashboard/auth/login.test.ts
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/itineraries/list.test.ts
  services/sso/src/__tests__/tokens/validate.test.ts
  services/sso/src/__tests__/users/getMe.test.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/controllers/auth/loginController.ts
  services/sso/src/controllers/dashboard/auth/login.ts
  services/sso/src/middleware/authenticate.ts
  services/sso/src/schemas/users/userSchema.ts
Labels: backend

#1076 1075-feuibug-fix-editableitem-type-bug
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/molecules/EditableItem.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/editableItem/index.stories.tsx
Labels: bug, frontend, ui

#1081 1053-fe-replace-topicseditableitem-in-front-with-editableitem-from-ui
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__tests__/molecules/TopicsEditableItem.test.tsx
  web/wiki/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  web/wiki/src/components/molecules/TopicsEditableItem.tsx
  web/wiki/src/components/molecules/index.ts
  web/wiki/src/components/organisms/TopicsManagerBoard.tsx
  web/wiki/src/hooks/useManageTopic.tsx
Labels: frontend

#1082 1066-be-wiki-delete-get-resources-topic-slug
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/categories/createCategory.test.ts
  services/wiki/src/__tests__/categories/patchCategory.test.ts
  services/wiki/src/__tests__/favorites/putFavoriteByUserId.test.ts
  services/wiki/src/__tests__/globalSetup.ts
  services/wiki/src/__tests__/resources/byId.test.ts
  services/wiki/src/__tests__/resources/byTopic.test.ts
  services/wiki/src/__tests__/resources/favorites.test.ts
  services/wiki/src/__tests__/resources/list.test.ts
  services/wiki/src/__tests__/resources/me.test.ts
  services/wiki/src/__tests__/resources/patch.test.ts
  services/wiki/src/__tests__/resources/post.test.ts
  services/wiki/src/__tests__/seen/create.test.ts
  services/wiki/src/__tests__/topics/getTopics.test.ts
  services/wiki/src/__tests__/vote/vote.test.ts
  services/wiki/src/controllers/index.ts
  services/wiki/src/controllers/resources/getResourcesByTopic.ts
  services/wiki/src/controllers/resources/list.ts
  services/wiki/src/openapi/config.ts
  services/wiki/src/openapi/routes/index.ts
  services/wiki/src/openapi/routes/resources/list.ts
  services/wiki/src/openapi/routes/resources/topic.ts
  services/wiki/src/routes/resourcesRouter.ts
  services/wiki/src/schemas/index.ts
  services/wiki/src/schemas/resource/resourcesListParamsSchema.ts
Labels: enhancement, backend

#1087 1060 fewiki complete cardresource test to cover votecounter logic added
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/CardResource.test.tsx
Labels: frontend

#1093 1086-fe-update-resources-endpoints-topicslug-and-categoryslug
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/hooks/useGetResources.test.tsx
  web/wiki/src/helpers/filters.ts
  web/wiki/src/pages/Category.tsx
  web/wiki/src/types/types.tsx
Labels: frontend

#1090 [BE][SSO] Update User status from INACTIVE to PENDING
  services/sso/CHANGELOG.md
  services/sso/db/init.sql
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/dashboard/auth/login.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/schemas/users/userSchema.ts
Labels: backend

#1025 Added Icon SelectGroup
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
  packages/ui/src/stories/atoms/Dropdown.stories.tsx
  packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
  packages/ui/src/stories/atoms/Dropdown/angular.svg
Labels: frontend

#1089 [BE][WIKI] Delete GET resources/topic/{topicId}
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package.json
  services/wiki/src/__tests__/resources/byTopic.test.ts
  services/wiki/src/__tests__/resources/list.test.ts
  services/wiki/src/controllers/index.ts
  services/wiki/src/controllers/resources/getResourcesByTopic.ts
  services/wiki/src/openapi/routes/index.ts
  services/wiki/src/openapi/routes/resources/topic.ts
  services/wiki/src/routes/resourcesRouter.ts
Labels: backend
