Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-07, with the labels that each got.

#1392 1382-feusuaris-fix-translations-for-roles-in-rolefilter
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__tests__/hooks/useRoles.test.tsx
  web/usuaris/src/__tests__/molecules/RoleFilter.test.tsx
  web/usuaris/src/components/molecules/RoleFilter.tsx
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/roles.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useRoles.tsx
Labels: bug, frontend

#1380 1379-be-wiki-add-operationid-to-all-zod-generated-swagger-endpoints
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/openapi/config.ts
  services/wiki/src/openapi/routes/auth/login.ts
  services/wiki/src/openapi/routes/auth/logout.ts
  services/wiki/src/openapi/routes/auth/me.ts
  services/wiki/src/openapi/routes/auth/register.ts
  services/wiki/src/openapi/routes/categories/create.ts
  services/wiki/src/openapi/routes/categories/get.ts
  services/wiki/src/openapi/routes/categories/patch.ts
  services/wiki/src/openapi/routes/favorites/put.ts
  services/wiki/src/openapi/routes/itinerary/get.ts
  services/wiki/src/openapi/routes/resources/create.ts
  services/wiki/src/openapi/routes/resources/favorites.ts
  services/wiki/src/openapi/routes/resources/id.ts
  services/wiki/src/openapi/routes/resources/list.ts
  services/wiki/src/openapi/routes/resources/me.ts
  services/wiki/src/openapi/routes/resources/patch.ts
  services/wiki/src/openapi/routes/seen/create.ts
  services/wiki/src/openapi/routes/topics/create.ts
  services/wiki/src/openapi/routes/topics/get.ts
  services/wiki/src/openapi/routes/topics/patch.ts
  services/wiki/src/openapi/routes/types.ts
  services/wiki/src/openapi/routes/users/get.ts
  services/wiki/src/openapi/routes/users/patch.ts
  services/wiki/src/openapi/routes/vote/vote.ts
Labels: documentation, backend

#1398 1397-be-sso-implement-knex-initial-config
  scripts/up_sso.sh
  services/sso/CHANGELOG.md
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/sonar-project.properties
  services/sso/src/config/index.ts
  services/sso/src/db/knexClient.ts
  services/sso/src/db/knexfile.ts
  services/sso/src/db/migrations/20240703064345_init.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1399 1385-besso-add-operationid-to-all-zod-generated-swagger-endpoints
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/openapi/routes/auth/login.ts
  services/sso/src/openapi/routes/auth/register.ts
  services/sso/src/openapi/routes/dashboard/auth/login.ts
  services/sso/src/openapi/routes/dashboard/auth/logout.ts
  services/sso/src/openapi/routes/dashboard/users/batchDelete.ts
  services/sso/src/openapi/routes/dashboard/users/delete.ts
  services/sso/src/openapi/routes/dashboard/users/getMe.ts
  services/sso/src/openapi/routes/dashboard/users/list.ts
  services/sso/src/openapi/routes/dashboard/users/update.ts
  services/sso/src/openapi/routes/dashboard/users/updateStatus.ts
  services/sso/src/openapi/routes/itineraries/list.ts
  services/sso/src/openapi/routes/tokens/refresh.ts
  services/sso/src/openapi/routes/tokens/validate.ts
  services/sso/src/openapi/routes/users/getMe.ts
  services/sso/src/openapi/routes/users/list.ts
  services/sso/src/openapi/routes/users/update.ts
Labels: documentation, backend

#1405 1225 fewiki login input to memorise dni and not autocomplete with email
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/components/organisms/Login.tsx
  web/wiki/src/components/organisms/Register.tsx
Labels: bug, frontend

#1363 746 fe implement openapi code generation for queries fetchers and types
  web/wiki/.eslintrc
  web/wiki/CHANGELOG.md
  web/wiki/openapi-codegen.config.ts
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/sonar-project.properties
  web/wiki/src/components/molecules/StatusFilterWidget.tsx
  web/wiki/src/components/molecules/TypesFilterWidget.tsx
  web/wiki/src/components/molecules/UserButton.tsx
  web/wiki/src/components/organisms/AccountAdmin.tsx
  web/wiki/src/components/organisms/CardResource.tsx
  web/wiki/src/components/organisms/CardResourceLink.tsx
  web/wiki/src/components/organisms/CategoriesList.tsx
  web/wiki/src/components/organisms/EditResource.tsx
  web/wiki/src/components/organisms/Login.tsx
  web/wiki/src/components/organisms/MyFavoritesList.tsx
  web/wiki/src/components/organisms/MyResources.tsx
  web/wiki/src/components/organisms/Register.tsx
  web/wiki/src/components/organisms/ResourceCardList.tsx
  web/wiki/src/components/organisms/ResourceForm.tsx
  web/wiki/src/components/organisms/Search.tsx
  web/wiki/src/components/organisms/TopicsManagerBoard.tsx
  web/wiki/src/components/organisms/TopicsRadioWidget.tsx
  web/wiki/src/components/organisms/UserProfileResourcesWidget.tsx
  web/wiki/src/context/AuthProvider.tsx
  web/wiki/src/hooks/useManageTopic.tsx
  web/wiki/src/openapi/openapiComponents.ts
  web/wiki/src/openapi/openapiContext.ts
  web/wiki/src/openapi/openapiFetcher.ts
  web/wiki/src/openapi/openapiParameters.ts
  web/wiki/src/openapi/openapiSchemas.ts
  web/wiki/src/pages/Category/Category.tsx
  web/wiki/src/pages/UserProfile.tsx
  web/wiki/src/types/index.tsx
  web/wiki/src/types/types.tsx
  web/wiki/src/utils/logOut.tsx
  web/wiki/tsconfig.json
Labels: enhancement, frontend

#1411 1407-besso-migrate-to-knex-post-dashboard-auth-login-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/config/index.ts
  services/sso/src/controllers/dashboard/auth/login.ts
  services/sso/src/db/knexClient.ts
  services/sso/src/db/knexfile.ts
Labels: enhancement, backend

#1417 1401-be-sso-migrate-to-knex-post-authlogin-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/unit/utils/userManager.test.ts
  services/sso/src/controllers/auth/loginController.ts
  services/sso/src/db/knexfile.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/db/migrations/20240703064345_init.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1420 1402-besso-migrate-to-knex-post-authregister-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/register.test.ts
  services/sso/src/controllers/auth/registerController.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1428 1408-besso-migrate-to-knex-GET-dashboardusersme-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/getMe.test.ts
  services/sso/src/controllers/dashboard/users/getMe.ts
  services/sso/src/openapi/config.ts
Labels: backend

#1440 1436-bewiki-specify-error-401-in-the-login-controler
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package.json
  services/wiki/src/openapi/routes/auth/login.ts
Labels: documentation, backend

#1444 1429-besso-migrate-to-knex-get-itinerarieslist-endpoints
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/controllers/itineraries/list.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/schemas/itineraries/itinerariesListSchema.ts
Labels: backend

#1446 1414-fewiki-fix-test-related-to-this-point-apiv1users
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/AccountAdmin.test.tsx
  web/wiki/src/__tests__/organisms/UsersManager.test.tsx
  web/wiki/src/components/organisms/AccountAdmin.tsx
  web/wiki/src/components/organisms/SettingsManager.tsx
  web/wiki/src/components/organisms/UsersManager.tsx
  web/wiki/src/components/organisms/index.ts
Labels: frontend

#1445 1443-bewiki-correct-swagger-pathapiv1resourcesfavoritescategoryslug
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/openapi/components/paramSchemas.ts
  services/wiki/src/openapi/config.ts
  services/wiki/src/openapi/routes/resources/favorites.ts
Labels: bug, backend

#1416 1410-Eliminate-avatarId-in-tests-that-use-useAuth-mock
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/molecules/FavoritesIcon.test.tsx
  web/wiki/src/__tests__/molecules/UserButton.test.tsx
  web/wiki/src/__tests__/organisms/CardResource.test.tsx
  web/wiki/src/__tests__/organisms/MyFavoritesList.test.tsx
  web/wiki/src/__tests__/organisms/MyResources.test.tsx
  web/wiki/src/__tests__/organisms/Navbar.test.tsx
  web/wiki/src/__tests__/organisms/SettingsManager.test.tsx
  web/wiki/src/__tests__/organisms/TopicsManagerBoard.test.tsx
  web/wiki/src/__tests__/organisms/UserProfileResourcesWidget.test.tsx
  web/wiki/src/__tests__/organisms/UsersManager.test.tsx
  web/wiki/src/__tests__/organisms/VotesDateController.test.tsx
  web/wiki/src/__tests__/pages/Category.test.tsx
  web/wiki/src/__tests__/pages/Home.test.tsx
  web/wiki/src/__tests__/pages/UserProfile.test.tsx
Labels: frontend, do not merge

#1447 1409-fewiki-fix-test-related-to-this-endpoint-apiv1topics
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/hooks/useManageTopic.test.tsx
  web/wiki/src/__tests__/organisms/SettingsManager.test.tsx
  web/wiki/src/__tests__/organisms/UsersManager.test.tsx
  web/wiki/src/components/organisms/TopicsManagerBoard.tsx
  web/wiki/src/hooks/useManageTopic.tsx
  web/wiki/src/openapi/openapiFetcher.ts
Labels: frontend

#1450 1430 besso migrate to knex patch usersupdate endpoints
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/unit/utils/userManager.test.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/controllers/users/update.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/openapi/config.ts
  services/sso/src/schemas/itineraries/itinerariesListSchema.ts
Labels: enhancement, backend

#1463 1454-fewikibug-fix-error-response-from-openapi-codegen-to-pass-tests-in-description
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/components/organisms/Login.tsx
  web/wiki/src/openapi/openapiComponents.ts
  web/wiki/src/openapi/openapiFetcher.ts
  web/wiki/src/openapi/openapiParameters.ts
  web/wiki/src/openapi/openapiSchemas.ts
Labels: bug, frontend
