Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-12, with the labels that each got.

#1573 1572 bewiki create huggingface repository apiv1resourcesgenerate description endpoint and testing
  services/wiki/.env
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/src/__tests__/globalSetup.ts
  services/wiki/src/__tests__/itineraries/list.test.ts
  services/wiki/src/__tests__/mocks/huggingFaceHandlers/generateText.ts
  services/wiki/src/__tests__/mocks/huggingFaceHandlers/index.ts
  services/wiki/src/__tests__/mocks/mswServer.ts
  services/wiki/src/__tests__/mocks/ssoHandlers/getMeUsersHandler.ts
  services/wiki/src/__tests__/mocks/ssoHandlers/updateUserHandler.ts
  services/wiki/src/__tests__/mocks/ssoHandlers/validateTokenHandler.ts
  services/wiki/src/__tests__/resources/generateDescription.test.ts
  services/wiki/src/__tests__/setup.ts
  services/wiki/src/controllers/index.ts
  services/wiki/src/controllers/resources/generateDescription.ts
  services/wiki/src/db/knexTypes.ts
  services/wiki/src/helpers/getLanguageInput.ts
  services/wiki/src/openapi/routes/index.ts
  services/wiki/src/openapi/routes/resources/generateDescription.ts
  services/wiki/src/repository/huggingFace/repo.test.ts
  services/wiki/src/repository/huggingFace/repo.ts
  services/wiki/src/routes/resourcesRouter.ts
  services/wiki/src/schemas/huggingFace/generateHFDescription.ts
  services/wiki/src/schemas/index.ts
  services/wiki/src/schemas/resource/generateDescriptionShema.ts
  services/wiki/tsconfig.json
Labels: enhancement, backend, tag/minor

#1575 fix-docker-build
  services/wiki/src/__tests__/repository/huggingFace/repo.test.ts
Labels: tag/minor

#1576 remove-migrate
  services/wiki/package.json
Labels: tag/patch

#1577 docker
  services/wiki/Dockerfile
Labels: tag/patch

#1578 binary-prisma
  services/wiki/prisma/schema.prisma
Labels: tag/patch

#1580 Created HTTPError to handle repo errors, updated openApi, updated generateDescriptionSchema
  services/wiki/openapi.yaml
  services/wiki/prisma/schema.prisma
  services/wiki/src/__tests__/repository/huggingFace/repo.test.ts
  services/wiki/src/controllers/resources/generateDescription.ts
  services/wiki/src/helpers/errors.ts
  services/wiki/src/openapi/routes/resources/generateDescription.ts
  services/wiki/src/repository/huggingFace/repo.ts
  services/wiki/src/schemas/resource/generateDescriptionShema.ts
Labels: enhancement, backend, tag/minor

#1581 prisma-fix
  services/wiki/Dockerfile
  services/wiki/package.json
Labels: tag/minor

#1583 prisma-fix
  services/wiki/Dockerfile
  services/wiki/package.json
Labels: tag/patch
