Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-10, with the labels that each got.

#1486 Updated delete endpoint to knex methods
  services/sso/CHANGELOG.md
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/delete.test.ts
  services/sso/src/controllers/dashboard/users/delete.ts
Labels: backend

#1490 [BE][SSO] Migrate to Knex ``DELETE dashboard/users`` endpoints
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/batchDelete.test.ts
  services/sso/src/controllers/dashboard/users/batchDelete.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1491 updated get userById to knex
  services/sso/CHANGELOG.md
  services/sso/package.json
  services/sso/src/__tests__/unit/utils/userManager.test.ts
  services/sso/src/db/managers/userManager.ts
Labels: backend

#1465 1432-besso-migrate-to-knex-get-dashboardusers-endpoints
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/openapi/config.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
  services/sso/src/utils/knex.queryBuilder.ts
Labels: documentation, backend

#1496 1495-besso-updated-tests-dashboardusersbatchDelete-to-Knex.
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/batchDelete.test.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1498 1418 besso ensure all types follow ttypename naming convention ssosrcschemas
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/controllers/auth/loginController.ts
  services/sso/src/controllers/auth/registerController.ts
  services/sso/src/controllers/dashboard/auth/login.ts
  services/sso/src/controllers/dashboard/users/getMe.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/controllers/dashboard/users/updateStatus.ts
  services/sso/src/controllers/tokens/refresh.ts
  services/sso/src/controllers/tokens/validate.ts
  services/sso/src/controllers/users/getMe.ts
  services/sso/src/controllers/users/list.ts
  services/sso/src/controllers/users/update.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/middleware/authorize.ts
  services/sso/src/openapi/config.ts
  services/sso/src/schemas/auth/loginSchema.ts
  services/sso/src/schemas/auth/registerSchema.ts
  services/sso/src/schemas/index.ts
  services/sso/src/schemas/itineraries/itinerariesListSchema.ts
  services/sso/src/schemas/tokens/validateSchema.ts
  services/sso/src/schemas/users/dashboardUsersListSchema.ts
  services/sso/src/schemas/users/dashboardUsersUpdateStatusSchema.ts
  services/sso/src/schemas/users/userSchema.ts
  services/sso/src/schemas/users/userUpdateSchema.ts
  services/sso/src/schemas/users/usersListSchema.ts
Labels: good first issue, backend

#1512 update
  services/sso/README.md
Labels: tag/patch

#1514 update
  services/sso/README.md
Labels: tag/patch

#1510 1500 besso migrate to knex test dashboard/users/delete.test
  services/sso/CHANGELOG.md
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/delete.test.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend

#1511 Updated TTypeNames in test files
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/openapi/config.ts
Labels: enhancement, backend, tag/patch

#1516 update
  services/sso/README.md
Labels: backend, tag/patch

#1517 update3
  services/sso/README.md
Labels: bug, backend, tag/patch

#1518 update
  services/sso/README.md
Labels: bug, backend, tag/patch

#1519 update
  services/sso/README.md
Labels: bug, backend, tag/minor

#1520 update
  services/sso/README.md
Labels: bug, backend, tag/minor

#1524 migrate to Knex globalSetup
  services/sso/openapi.yaml
  services/sso/src/__tests__/globalSetup.ts
Labels: enhancement, backend, tag/minor

#1505 updated dashboard/users/update.test.ts to knex methods
  services/sso/CHANGELOG.md
  services/sso/src/__tests__/dashboard/users/update.test.ts
Labels: enhancement, backend, tag/minor

#1531 create knex.ts file with Knex setup and configuration
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/config/config.ts
  services/wiki/src/db/knex.ts
  services/wiki/src/openapi/config.ts
Labels: enhancement, backend, tag/minor

#1535 updated create category controller and test to knex methods
  .github/workflows/pr_check_service_wiki.yml
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/categories/create.test.ts
  services/wiki/src/controllers/categories/create.ts
  services/wiki/src/openapi/routes/index.ts
  services/wiki/src/openapi/routes/media.ts
Labels: enhancement, backend, tag/minor

#1555 updated users controller and testing
  services/wiki/src/__tests__/users/get.test.ts
  services/wiki/src/controllers/users/get.ts
Labels: enhancement, backend, tag/minor

#1556 1548-bewiki-migrate-vote-controller-put-to-knex-methods
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package.json
  services/wiki/src/__tests__/vote/vote.test.ts
  services/wiki/src/controllers/vote/put.ts
  services/wiki/src/openapi/config.ts
Labels: backend, tag/minor
