Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-04, with the labels that each got.

#1103 1094-fe-fix-errors-in-category-page
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/ResourceCardList.test.tsx
  web/wiki/src/__tests__/organisms/Search.test.tsx
  web/wiki/src/__tests__/pages/Category.test.tsx
  web/wiki/src/components/molecules/SelectLanguage.tsx
  web/wiki/src/components/molecules/UserButton.tsx
  web/wiki/src/components/organisms/Navbar.tsx
  web/wiki/src/components/organisms/ResourceCardList.tsx
  web/wiki/src/components/organisms/Search.tsx
  web/wiki/src/pages/Category/Category.styles.ts
  web/wiki/src/pages/Category/Category.tsx
  web/wiki/src/pages/Category/index.ts
Labels: frontend

#1109 [BE][WIKI]Refactor GET resources/id/{resourceId} to /resources/{id}
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/resources/byId.test.ts
  services/wiki/src/controllers/resources/getResourcesById.ts
  services/wiki/src/openapi/routes/resources/id.ts
  services/wiki/src/routes/resourcesRouter.ts
Labels: backend

#1100 [FE][BUG] Check Button.test in stroybook not passing tests, button when render is active?
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Button.test.tsx
  packages/ui/src/components/atoms/Button.tsx
Labels: frontend

#1121 1119-be-wiki-implement-endpoint-to-serve-openapi-yaml
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package.json
  services/wiki/src/__tests__/openapi/serveOpenApiFile.test.ts
  services/wiki/src/middleware/errorMiddleware.ts
  services/wiki/src/middleware/serveOpenApiFile.ts
  services/wiki/src/openapi/config.ts
  services/wiki/src/server.ts
Labels: enhancement, backend

#1133 1078 be sso refactor auth
  services/sso/CHANGELOG.md
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/middleware/authenticate.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
Labels: backend

#1120 883-fe-sso-always-requires-login-and-only-accessible-for-admin-users
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/context/AuthProvider.test.tsx
  web/usuaris/src/__tests__/hooks/useLogin.test.tsx
  web/usuaris/src/__tests__/main.test.tsx
  web/usuaris/src/__tests__/organisms/Login.test.tsx
  web/usuaris/src/__tests__/organisms/Navbar.test.tsx
  web/usuaris/src/__tests__/pages/Home.test.tsx
  web/usuaris/src/components/organisms/Login.tsx
  web/usuaris/src/components/organisms/Navbar.tsx
  web/usuaris/src/components/organisms/index.ts
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/context/AuthProvider.tsx
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useLogin.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/main.tsx
  web/usuaris/src/pages/Home.tsx
  web/usuaris/src/utils/.gitkeep
Labels: frontend

#1138 1134-be-sso-add-endpoint-with-get-me-for-dashboard
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/getMe.test.ts
  services/sso/src/controllers/dashboard/users/getMe.ts
  services/sso/src/openapi/components/responses.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/dashboard/users/getMe.ts
  services/sso/src/openapi/routes/index.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
Labels: enhancement, backend

#1147 1146-fe-update-dropdown-in-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
Labels: enhancement, frontend, ui

#1152 1148-fesso-display-dashboard-after-login-successful-not-working
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/organisms/UsersTable.tsx
  web/usuaris/src/context/AuthProvider.tsx
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
Labels: frontend

#1153 1124-fesso-add-itinerary-dropdown-selector
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetItineraries.test.tsx
  web/usuaris/src/__tests__/molecules/ItineraryDropdown.test.tsx
  web/usuaris/src/__tests__/organisms/FiltersWidget.test.tsx
  web/usuaris/src/__tests__/test-utils.tsx
  web/usuaris/src/assets/icons/angular.svg
  web/usuaris/src/assets/icons/bbdd.svg
  web/usuaris/src/assets/icons/data-science.svg
  web/usuaris/src/assets/icons/index.ts
  web/usuaris/src/assets/icons/java.svg
  web/usuaris/src/assets/icons/javascript.svg
  web/usuaris/src/assets/icons/nodejs-logo.svg
  web/usuaris/src/assets/icons/php.svg
  web/usuaris/src/assets/icons/react.svg
  web/usuaris/src/components/molecules/ItineraryDropdown.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useGetItineraries.tsx
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1151 1150-be-sso-error-code-change-498-to-401-for-invalid-and-missing-tokens
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package.json
  services/sso/src/__tests__/tokens/validate.test.ts
  services/sso/src/__tests__/users/getMe.test.ts
  services/sso/src/openapi/components/responses.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/users/update.ts
  services/sso/src/utils/errors.ts
Labels: enhancement, backend

#1159 1137-fesso-add-checkbox-and-delete-button-to-userstable
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/assets/icons/delete.svg
  web/usuaris/src/assets/icons/index.ts
  web/usuaris/src/components/molecules/Table.tsx
  web/usuaris/src/components/organisms/UsersTable.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.styles.ts
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/components/organisms/index.ts
  web/usuaris/src/context/AuthProvider.tsx
Labels: frontend

#1162 1141-be-wiki-log-503-error-to-stdout
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/auth/login.test.ts
  services/wiki/src/__tests__/auth/register.test.ts
  services/wiki/src/__tests__/helpers/checkInvalidToken.ts
  services/wiki/src/__tests__/media/media.test.ts
  services/wiki/src/__tests__/mocks/ssoHandlers/validateTokenHandler.ts
  services/wiki/src/__tests__/users/patchUser.test.ts
  services/wiki/src/helpers/errors.ts
  services/wiki/src/helpers/sso/getMeUsers.ts
  services/wiki/src/helpers/sso/listItineraries.ts
  services/wiki/src/helpers/sso/listUsers.ts
  services/wiki/src/helpers/sso/login.ts
  services/wiki/src/helpers/sso/register.ts
  services/wiki/src/helpers/sso/updateUser.ts
  services/wiki/src/helpers/sso/validate.ts
  services/wiki/src/middleware/errorMiddleware.ts
  services/wiki/src/openapi/components/responses/authMiddleware.ts
  services/wiki/src/openapi/config.ts
  services/wiki/src/openapi/routes/auth/login.ts
  services/wiki/src/openapi/routes/auth/me.ts
  services/wiki/src/openapi/routes/categories/create.ts
  services/wiki/src/openapi/routes/categories/patch.ts
  services/wiki/src/openapi/routes/favorites/put.ts
  services/wiki/src/openapi/routes/media.ts
  services/wiki/src/openapi/routes/resources/create.ts
  services/wiki/src/openapi/routes/resources/favorites.ts
  services/wiki/src/openapi/routes/resources/list.ts
  services/wiki/src/openapi/routes/resources/me.ts
  services/wiki/src/openapi/routes/resources/patch.ts
  services/wiki/src/openapi/routes/seen/create.ts
  services/wiki/src/openapi/routes/topics/create.ts
  services/wiki/src/openapi/routes/topics/patch.ts
  services/wiki/src/openapi/routes/users/get.ts
  services/wiki/src/openapi/routes/users/patch.ts
  services/wiki/src/openapi/routes/vote/vote.ts
Labels: enhancement, backend

#1168 1164-feui-fix-dropdown-to-allow-deselect
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
Labels: frontend, ui

#1166 1128-be-sso-add-patch-endpoint
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/update.test.ts
  services/sso/src/controllers/users/update.ts
  services/sso/src/middleware/authenticate.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/dashboard/users/update.ts
  services/sso/src/openapi/routes/index.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
  services/sso/src/schemas/users/dashboardUserUpdateSchema.ts
  services/sso/src/schemas/users/userUpdateSchema.ts
Labels: backend

#1175 1165-fesso-add-blockactivate-user-functionality-to-userstable
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useUpdateUser.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useUpdateUser.tsx
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1180 1178-fesso-add-dni-colum-to-userstable
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/types/types.tsx
Labels: enhancement, frontend

#1184 1127-be-sso-add-endpoint-to-block-multiple-users-to-dashboard
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/updateStatus.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/controllers/dashboard/users/updateStatus.ts
  services/sso/src/openapi/components/responses.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/dashboard/users/updateStatus.ts
  services/sso/src/openapi/routes/index.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
  services/sso/src/schemas/users/dashboardUsersUpdateStatusSchema.ts
  services/sso/src/schemas/users/userSchema.ts
Labels: enhancement, backend

#1190 1188 Add role filter option
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/openapi/routes/dashboard/users/list.ts
  services/sso/src/schemas/users/dashboardUsersListQuerySchema.ts
  services/sso/src/schemas/users/dashboardUsersListSchema.ts
  services/sso/src/schemas/users/userSchema.ts
Labels: backend

#1177 1167 Refactor soft deleted related querys
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/users/getMe.test.ts
  services/sso/src/__tests__/users/list.test.ts
  services/sso/src/controllers/auth/loginController.ts
  services/sso/src/controllers/users/getMe.ts
  services/sso/src/controllers/users/list.ts
Labels: backend

#1193 1192-feui-add-callback-function-to-handle-search-value-in-search-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/Search/Search.test.tsx
  packages/ui/src/components/molecules/Search/Search.tsx
  packages/ui/src/components/molecules/Search/index.ts
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/molecules/Search/Search.stories.ts
Labels: frontend, ui

#1194 1170-fesso-implement-itinerary-filter
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/molecules/ItineraryDropdown.test.tsx
  web/usuaris/src/__tests__/organisms/FiltersWidget.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/ItineraryDropdown.tsx
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/filters.ts
  web/usuaris/src/hooks/useGetUsers.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/pages/Home.tsx
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1201 1199-fe-ui-add-dropdown-features
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
  packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
Labels: frontend, ui

#1205 1126-add-search-field
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/organisms/FiltersWidget.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/Table.tsx
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/useGetUsers.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
Labels: frontend
