Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-05, with the labels that each got.

#1219 1218-feuibug-delete-unnecessary-dependency-in-search-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/molecules/Search/Search.tsx
Labels: bug, frontend, ui

#1212 1186-fesso-filtrado-de-fechas-funcional-y-con-opcion-de-deseleccionar
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/molecules/DateRange.test.tsx
  web/usuaris/src/__tests__/molecules/ItineraryDropdown.test.tsx
  web/usuaris/src/__tests__/organisms/FiltersWidget.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/DateRange.tsx
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/helpers/filters.ts
  web/usuaris/src/pages/Home.tsx
Labels: frontend

#1216 1214-feui-fix-dropdown-to-allow-custom-data-testid
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
Labels: bug, frontend, ui

#1215 1196-be-sso-refactor-dashboarduserslist-query
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/unit/queryBuilder.test.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/utils/queryBuilder.ts
Labels: backend

#1231 1226-fesso-refetch-after-activate-block-unblock-user-to-update-user-status
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__tests__/hooks/useUpdateUser.test.tsx
  web/usuaris/src/hooks/useUpdateUser.tsx
Labels: frontend

#1207 1125-fesso-add-status-dropdown
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/hooks/useUpdateUser.test.tsx
  web/usuaris/src/__tests__/molecules/StatusDropdown.test.tsx
  web/usuaris/src/__tests__/organisms/FiltersWidget.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/ItineraryDropdown.tsx
  web/usuaris/src/components/molecules/StatusDropdown.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1211 1187-add-rol-column-and-filter
  package-lock.json
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
  web/usuaris/src/__tests__/molecules/RoleFilter.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/RoleFilter.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/components/organisms/SideMenu.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.styles.ts
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/roles.ts
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/types/types.tsx
Labels: frontend

#1237 1235-bewiki-fix-logout-endpoint-to-ensure-authtoken-and-refreshtoken-cookies-are-properly-cleared
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package-lock.json
  services/wiki/package.json
  services/wiki/src/__tests__/auth/logout.test.ts
  services/wiki/src/controllers/auth/logoutController.ts
Labels: bug, backend

#1217 1174 fe sso implement delete users feature
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useDeleteUser.test.tsx
  web/usuaris/src/__tests__/molecules/DeleteConfirmationModal.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/components/molecules/DeleteConfirmationModal.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/filters.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useDeleteUser.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
Labels: frontend

#1244 1213 besso add endpoint for deleting multiple users in the dashboard
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/dashboard/users/batchDelete.test.ts
  services/sso/src/controllers/dashboard/users/batchDelete.ts
  services/sso/src/openapi/routes/dashboard/users/batchDelete.ts
  services/sso/src/openapi/routes/index.ts
  services/sso/src/routes/dashboard/usersRoutes.ts
Labels: backend

#1249 be sso implement deleted in the get /dashboard/users filter
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/unit/queryBuilder.test.ts
  services/sso/src/openapi/config.ts
  services/sso/src/schemas/users/dashboardUsersListQuerySchema.ts
  services/sso/src/utils/queryBuilder.ts
Labels: backend

#1238 1183-be-sso-implement-refresh-token-functionality
  services/sso/.env
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/sonar-project.properties
  services/sso/src/__tests__/auth/login.test.ts
  services/sso/src/__tests__/auth/register.test.ts
  services/sso/src/__tests__/dashboard/users/batchDelete.test.ts
  services/sso/src/__tests__/dashboard/users/delete.test.ts
  services/sso/src/__tests__/dashboard/users/getMe.test.ts
  services/sso/src/__tests__/dashboard/users/list.test.ts
  services/sso/src/__tests__/dashboard/users/update.test.ts
  services/sso/src/__tests__/dashboard/users/updateStatus.test.ts
  services/sso/src/__tests__/globalSetup.ts
  services/sso/src/__tests__/helpers/testHelpers.ts
  services/sso/src/__tests__/tokens/refresh.test.ts
  services/sso/src/__tests__/tokens/validate.test.ts
  services/sso/src/__tests__/unit/middleware/authenticate.test.ts
  services/sso/src/__tests__/unit/utils/queryBuilder.test.ts
  services/sso/src/__tests__/unit/utils/userManager.test.ts
  services/sso/src/__tests__/unit/utils/validateUserAndToken.test.ts
  services/sso/src/__tests__/users/getMe.test.ts
  services/sso/src/__tests__/users/list.test.ts
  services/sso/src/__tests__/users/update.test.ts
  services/sso/src/app.ts
  services/sso/src/config/index.ts
  services/sso/src/controllers/auth/loginController.ts
  services/sso/src/controllers/auth/registerController.ts
  services/sso/src/controllers/dashboard/auth/login.ts
  services/sso/src/controllers/dashboard/users/batchDelete.ts
  services/sso/src/controllers/dashboard/users/delete.ts
  services/sso/src/controllers/dashboard/users/getMe.ts
  services/sso/src/controllers/dashboard/users/list.ts
  services/sso/src/controllers/dashboard/users/updateStatus.ts
  services/sso/src/controllers/itineraries/list.ts
  services/sso/src/controllers/tokens/refresh.ts
  services/sso/src/controllers/users/getMe.ts
  services/sso/src/controllers/users/list.ts
  services/sso/src/controllers/users/update.ts
  services/sso/src/db/client.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/middleware/authenticate.ts
  services/sso/src/openapi/components/responses.ts
  services/sso/src/openapi/config.ts
  services/sso/src/openapi/routes/index.ts
  services/sso/src/openapi/routes/tokens/refresh.ts
  services/sso/src/routes/tokensRoutes.ts
  services/sso/src/schemas/users/userSchema.ts
  services/sso/src/utils/auth.ts
  services/sso/src/utils/authHelper.ts
  services/sso/src/utils/jwtAuth.ts
Labels: enhancement, backend

#1104 1029 feusuaris selector de idiomas
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__tests__/main.test.tsx
  web/usuaris/src/__tests__/molecules/SelectLanguage.test.tsx
  web/usuaris/src/__tests__/organisms/Navbar.test.tsx
  web/usuaris/src/components/molecules/SelectLanguage.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/Navbar.tsx
  web/usuaris/src/constants/index.ts
  web/usuaris/src/constants/languages.ts
Labels: frontend

#1262 1258-fewiki-expand-description-field-in-new-resource-form
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/components/organisms/ResourceForm.tsx
Labels: frontend

#1266 1264-feui-add-resetselectedvalue-prop-in-dropdown-component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Dropdown.test.tsx
  packages/ui/src/components/atoms/Dropdown.tsx
Labels: frontend, ui

#1267 1139-fewiki-when-logging-in-with-wrong-credentials-it-appears-as-correct
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__tests__/organisms/Login.test.tsx
  web/wiki/src/components/organisms/Login.tsx
  web/wiki/src/components/organisms/Register.tsx
  web/wiki/src/helpers/fetchers.ts
  web/wiki/src/locales/cat.json
  web/wiki/src/locales/en.json
  web/wiki/src/locales/es.json
Labels: frontend

#1263 1260-sort-columns-by-header-on-users-table
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__tests__/molecules/Table.test.tsx
  web/usuaris/src/assets/icons/index.ts
  web/usuaris/src/assets/icons/sort-up.svg
  web/usuaris/src/components/molecules/Table.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.styles.ts
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
Labels: frontend

#1277 1276-be-sso-ensure-get-users-endpoint-returns-only-active-users
  services/sso/CHANGELOG.md
  services/sso/openapi.yaml
  services/sso/package-lock.json
  services/sso/package.json
  services/sso/src/__tests__/unit/utils/userManager.test.ts
  services/sso/src/controllers/users/list.ts
  services/sso/src/db/managers/userManager.ts
  services/sso/src/openapi/config.ts
Labels: bug, backend

#1275 1273-be-wiki-include-only-resources-with-active-and-existing-users-in-get-resources
  services/wiki/CHANGELOG.md
  services/wiki/openapi.yaml
  services/wiki/package.json
  services/wiki/src/__tests__/resources/byId.test.ts
  services/wiki/src/__tests__/resources/list.test.ts
  services/wiki/src/controllers/resources/getResourcesByUserId.ts
  services/wiki/src/controllers/resources/list.ts
  services/wiki/src/helpers/attachUserNamesToResources.ts
  services/wiki/src/helpers/index.ts
  services/wiki/src/helpers/markFavorites.ts
  services/wiki/src/openapi/config.ts
Labels: bug, backend

#1259 1185-fesso-boton-de-aceptar-con-nuevas-condiciones
  web/usuaris/CHANGELOG.md
  web/usuaris/package-lock.json
  web/usuaris/package.json
  web/usuaris/src/__mocks__/handlers.ts
  web/usuaris/src/__tests__/hooks/useDeleteMultipleUsers.test.tsx
  web/usuaris/src/__tests__/hooks/useUpdateUsersStatus.test.tsx
  web/usuaris/src/__tests__/molecules/ActionsDropdown.test.tsx
  web/usuaris/src/__tests__/molecules/DeleteConfirmationModal.test.tsx
  web/usuaris/src/__tests__/organisms/UsersTable.test.tsx
  web/usuaris/src/__tests__/pages/Home.test.tsx
  web/usuaris/src/components/molecules/ActionsDropdown.tsx
  web/usuaris/src/components/molecules/DeleteConfirmationModal.tsx
  web/usuaris/src/components/molecules/SelectLanguage.tsx
  web/usuaris/src/components/molecules/index.ts
  web/usuaris/src/components/organisms/FiltersWidget.tsx
  web/usuaris/src/components/organisms/UsersTable/UsersTable.tsx
  web/usuaris/src/constants/urls.ts
  web/usuaris/src/helpers/fetchers.ts
  web/usuaris/src/helpers/index.ts
  web/usuaris/src/hooks/index.ts
  web/usuaris/src/hooks/useDeleteMultipleUsers.tsx
  web/usuaris/src/hooks/useUpdateUsersStatus.tsx
  web/usuaris/src/locales/cat.json
  web/usuaris/src/locales/en.json
  web/usuaris/src/locales/es.json
  web/usuaris/src/pages/Home.tsx
  web/usuaris/src/types/index.tsx
  web/usuaris/src/types/types.tsx
Labels: frontend

#1281 1274-fesso-rearrange-sorting-in-headers-at-table-component-to-include-incon-in-all-conditions
  web/usuaris/CHANGELOG.md
  web/usuaris/package.json
  web/usuaris/src/__tests__/molecules/Table.test.tsx
  web/usuaris/src/components/molecules/Table.tsx
Labels: frontend

#1291 1289-fewiki-include-banners-list-in-home-page
  web/wiki/CHANGELOG.md
  web/wiki/package-lock.json
  web/wiki/package.json
  web/wiki/src/__mocks__/handlers.ts
  web/wiki/src/__tests__/hooks/useGetBanners.test.tsx
  web/wiki/src/__tests__/pages/Home.test.tsx
  web/wiki/src/constants/urls.ts
  web/wiki/src/helpers/fetchers.ts
  web/wiki/src/hooks/index.ts
  web/wiki/src/hooks/useGetBanners.tsx
  web/wiki/src/pages/Home.tsx
  web/wiki/src/types/index.tsx
  web/wiki/src/types/types.tsx
Labels: frontend

#1306 1303-remove-banners-from-homepage
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/__mocks__/handlers.ts
  web/wiki/src/__tests__/hooks/useGetBanners.test.tsx
  web/wiki/src/__tests__/pages/Home.test.tsx
  web/wiki/src/constants/urls.ts
  web/wiki/src/helpers/fetchers.ts
  web/wiki/src/hooks/index.ts
  web/wiki/src/hooks/useGetBanners.tsx
  web/wiki/src/pages/Home.tsx
  web/wiki/src/types/index.tsx
  web/wiki/src/types/types.tsx
Labels: frontend
