Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-09, with the labels that each got.

#1462 1457-fewiki-replace-favMutation-in-favoritesIcon-component-with-corresponding-openapi-generated-fetcher
  web/wiki/CHANGELOG.md
  web/wiki/package.json
  web/wiki/src/components/molecules/FavoritesIcon.tsx
Labels: frontend

#1456 1455-fewikidocs-update-readme-with-new-repository-structure-and-generators-info
  web/wiki/README.md
  web/wiki/package.json
Labels: documentation, frontend

#1475 create .nvmrc file with node v18.17.1
  services/sso/.nvmrc
Labels: backend

#1477 1434 besso correct the error handler for unique email or dni in the register controller
  services/sso/CHANGELOG.md
  services/sso/package.json
  services/sso/src/controllers/auth/registerController.ts
Labels: backend
