Repository IT-Academy-BCN/ita-wiki, pull requests merged in 2024-01, with the labels that each got.

#772 771-be-implement-get-itinerary-from-sso-and-delete-specialization
  back/CHANGELOG.md
  back/openapi.yaml
  back/package.json
  back/prisma/data/users.ts
  back/prisma/migrations/20231220093308_deleted_specialization/migration.sql
  back/prisma/schema.prisma
  back/prisma/seed.ts
  back/src/__tests__/auth/register.test.ts
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/itinerary/get.test.ts
  back/src/__tests__/mocks/ssoServer.ts
  back/src/__tests__/users/patchUser.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/controllers/auth/loginController.ts
  back/src/controllers/auth/register.ts
  back/src/controllers/index.ts
  back/src/controllers/itinerary/get.ts
  back/src/helpers/handleSso.ts
  back/src/helpers/index.ts
  back/src/helpers/sso/getItineraries.ts
  back/src/helpers/sso/getUser.ts
  back/src/helpers/sso/index.ts
  back/src/helpers/sso/login.ts
  back/src/helpers/sso/pathSso.ts
  back/src/helpers/sso/register.ts
  back/src/helpers/sso/validate.ts
  back/src/helpers/ssoHandler.ts
  back/src/middleware/authenticate.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/itinerary.ts
  back/src/openapi/config.ts
  back/src/openapi/routes/index.ts
  back/src/openapi/routes/itinerary/get.ts
  back/src/routes/index.ts
  back/src/routes/itinerary.ts
  back/src/routes/routes.ts
  back/src/schemas/itinerary/itineraryGetSchema.ts
  back/src/schemas/itinerary/itinerarySchema.ts
  back/src/schemas/sso/ssoGetItineraries.ts
  back/src/schemas/sso/ssoGetUser.ts
  back/src/schemas/users/userRegisterSchema.ts
  back/src/schemas/users/userSchema.ts
  back/src/server.ts
Labels: backend

#763 760-fe-migrate-button-to-storybook
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Button.test.tsx
  packages/ui/src/components/atoms/Button.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Button.stories.ts
Labels: enhancement, frontend

#784 783-fe-update-register-schema
  packages/schemas/CHANGELOG.md
  packages/schemas/README.md
  packages/schemas/package-lock.json
  packages/schemas/package.json
  packages/schemas/src/Register.ts
Labels: frontend

#776 756-fe-migrate-checkbox-component-to-storybook
  packages/package-lock.json
  packages/ui/.storybook/preview-head.html
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/sonar-project.properties
  packages/ui/src/__tests__/atoms/CheckBox.test.tsx
  packages/ui/src/__tests__/setup.ts
  packages/ui/src/components/atoms/Checkbox.tsx
  packages/ui/src/components/atoms/Label.tsx
  packages/ui/src/stories/atoms/Checkbox.stories.ts
  packages/ui/src/styles/FlexBox.ts
  packages/ui/src/styles/index.ts
Labels: frontend

#758 743-febug-fix-topic-selected-when-switching-between-categories
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/organisms/TopicsRadioWidget.test.tsx
  front/src/components/organisms/TopicsRadioWidget.tsx
  front/src/pages/Category.tsx
Labels: bug, frontend

#789 777 fe migrate hamburger menu
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/HamburguerMenu.test.tsx
  packages/ui/src/components/atoms/HamburgerMenu.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/HamburgerMenu.stories.ts
Labels: enhancement, frontend

#752 744-fe-update-specialty-dropdown-from-sso-service
  front/CHANGELOG.md
  front/package-lock.json
  front/package.json
  front/src/__mocks__/handlers.ts
  front/src/__tests__/hooks/useGetItineraries.test.tsx
  front/src/__tests__/hooks/useRegister.test.tsx
  front/src/__tests__/organisms/Register.test.tsx
  front/src/__tests__/organisms/SettingsManager.test.tsx
  front/src/components/organisms/Register.tsx
  front/src/constants/urls.ts
  front/src/helpers/fetchers.ts
  front/src/helpers/index.ts
  front/src/hooks/index.ts
  front/src/hooks/useGetItineraries.tsx
  front/src/locales/cat.json
  front/src/locales/en.json
  front/src/locales/es.json
  front/src/types/index.tsx
  front/src/types/types.tsx
Labels: enhancement, frontend

#790 775-fe-migrate-backbutton-to-storybook
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview-head.html
  packages/ui/.storybook/preview.ts
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Icon.test.tsx
  packages/ui/src/__tests__/molecules/BackButton.test.tsx
  packages/ui/src/components/atoms/Icon.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/components/molecules/BackButton.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/atoms/Icon.stories.ts
  packages/ui/src/stories/molecules/BackButton.stories.ts
Labels: enhancement, frontend

#796 794-be-sso-bug-fix-dni-letter-is-saved-in-database-and-used-during-lo…
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/auth/login.test.ts
  sso/src/__tests__/auth/register.test.ts
  sso/src/controllers/auth/loginController.ts
  sso/src/controllers/auth/registerController.ts
  sso/src/openapi/config.ts
  sso/src/schemas/auth/loginSchema.ts
Labels: bug, backend

#727 726-febug-fix-filter-applied-when-clicking-on-newresource-radiobutton
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/molecules/InputGroup.test.tsx
  front/src/__tests__/molecules/SelectGroup.test.tsx
  front/src/__tests__/molecules/TextareaGroup.test.tsx
  front/src/components/atoms/CheckBox.tsx
  front/src/components/atoms/Radio.tsx
  front/src/components/molecules/InputGroup.tsx
  front/src/components/molecules/SelectGroup.tsx
  front/src/components/molecules/TextareaGroup.tsx
  front/src/components/organisms/ResourceForm.tsx
  front/src/utils/newId.ts
Labels: bug, frontend

#806 804-be-bug-fix-userid-validation-to-use-cuid2-format-in-zod-schema
  back/CHANGELOG.md
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/mocks/ssoServer.ts
  back/src/openapi/config.ts
  back/src/schemas/resource/resourceSchema.ts
  back/src/schemas/users/userSchema.ts
Labels: bug, backend

#795 755-migrate InputGroup to UI
  packages/ui/.storybook/preview-head.html
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/ValidationMessage.test.tsx
  packages/ui/src/__tests__/molecules/InputGroup.test.tsx
  packages/ui/src/components/atoms/Icon.tsx
  packages/ui/src/components/atoms/ValidationMessage.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/components/molecules/BackButton.tsx
  packages/ui/src/components/molecules/InputGroup.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/atoms/Icon.stories.ts
  packages/ui/src/stories/atoms/ValidationMessage.stories.ts
  packages/ui/src/stories/molecules/InputGroup.stories.ts
Labels: enhancement, frontend

#813 809 fe sso create the initial structure of sso front
  sso_front/.eslintrc.cjs
  sso_front/.gitignore
  sso_front/CHANGELOG.md
  sso_front/README.md
  sso_front/index.html
  sso_front/package-lock.json
  sso_front/package.json
  sso_front/src/__mocks__/.gitkeep
  sso_front/src/__tests__/.gitkeep
  sso_front/src/assets/.gitkeep
  sso_front/src/components/.gitkeep
  sso_front/src/constants/.gitkeep
  sso_front/src/helpers/.gitkeep
  sso_front/src/hooks/.gitkeep
  sso_front/src/main.tsx
  sso_front/src/pages/.gitkeep
  sso_front/src/styles/.gitkeep
  sso_front/src/types/.gitkeep
  sso_front/src/utils/.gitkeep
  sso_front/src/vite-env.d.ts
  sso_front/tsconfig.json
  sso_front/tsconfig.node.json
  sso_front/vite.config.ts
Labels: enhancement, frontend

#824 817-be-sso-migration-of-role-management-functionality-into-the-sso
  back/CHANGELOG.md
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/prisma/data/users.ts
  back/prisma/migrations/20231220093308_remove_specialization/migration.sql
  back/prisma/migrations/20240115182237_remove_role/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/helpers/checkRoleAccess.test.ts
  back/src/__tests__/mocks/ssoServer.ts
  back/src/__tests__/users/patchUser.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/helpers/checkRoleAccess.ts
  back/src/helpers/sso/getUser.ts
  back/src/middleware/authorize.ts
  back/src/openapi/config.ts
  back/src/routes/categoriesRouter.ts
  back/src/routes/topics.ts
  back/src/routes/users.ts
  back/src/schemas/sso/ssoGetUser.ts
  back/src/schemas/users/userSchema.ts
  sso/CHANGELOG.md
  sso/db/init.sql
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/auth/register.test.ts
  sso/src/__tests__/globalSetup.ts
  sso/src/__tests__/user/get.test.ts
  sso/src/controllers/user/get.ts
  sso/src/openapi/components/responses.ts
  sso/src/openapi/config.ts
  sso/src/schemas/auth/userSchema.ts
Labels: backend

#828 827-be-bug-fix-prisma-migration
  back/CHANGELOG.md
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/prisma/migrations/20231220093308_deleted_specialization/migration.sql
  back/src/openapi/config.ts
Labels: bug, backend

#818 fe-sso_front-config
  sso_front/.dockerignore
  sso_front/.eslintrc
  sso_front/.eslintrc.cjs
  sso_front/.gitignore
  sso_front/.pretierrc
  sso_front/Dockerfile
  sso_front/index.html
  sso_front/nginx.conf.template
  sso_front/package-lock.json
  sso_front/package.json
  sso_front/src/main.tsx
  sso_front/tsconfig.json
  sso_front/tsconfig.node.json
  sso_front/vite.config.ts
Labels: enhancement, frontend

#816 780 fe migrate modal
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Text.test.tsx
  packages/ui/src/__tests__/atoms/Title.test.tsx
  packages/ui/src/__tests__/molecules/Modal.test.tsx
  packages/ui/src/components/atoms/Text.ts
  packages/ui/src/components/atoms/Title.ts
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/components/molecules/Modal.tsx
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/atoms/Icon.stories.ts
  packages/ui/src/stories/atoms/Text.stories.ts
  packages/ui/src/stories/atoms/Title.stories.ts
  packages/ui/src/stories/molecules/Modal.stories.tsx
  packages/ui/src/styles/font.ts
Labels: enhancement, frontend

#823 778 fe migrate radio
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Radio.test.tsx
  packages/ui/src/components/atoms/Radio.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Radio.stories.ts
Labels: enhancement, frontend

#839 834-fe-ui-inputgroup-use-default-values
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/stories/molecules/InputGroup.stories.ts
Labels: bug, enhancement, frontend

#842 768-be-sso-update-user-information
  back/CHANGELOG.md
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/src/__tests__/users/patchUser.test.ts
  back/src/openapi/config.ts
  sso/CHANGELOG.md
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/user/patch.test.ts
  sso/src/controllers/token/validate.ts
  sso/src/controllers/user/get.ts
  sso/src/controllers/user/patch.ts
  sso/src/middleware/authenticate.ts
  sso/src/middleware/authorize.ts
  sso/src/openapi/config.ts
  sso/src/openapi/routes/index.ts
  sso/src/openapi/routes/user/patch.ts
  sso/src/routes/userRoutes.ts
  sso/src/schemas/auth/loginSchema.ts
  sso/src/schemas/auth/registerSchema.ts
  sso/src/schemas/index.ts
  sso/src/schemas/user/userPatchSchema.ts
  sso/src/schemas/user/userSchema.ts
  sso/src/utils/checkRoleAccess.ts
Labels: enhancement, backend

#837 831-fe-fix-modal
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/molecules/Modal.tsx
  packages/ui/src/stories/molecules/Modal.stories.tsx
Labels: bug, frontend

#838 833 fix UI button component
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/stories/atoms/Button.stories.ts
Labels: frontend, ui

#848 779-fe-migrate-tabs
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/molecules/Tabs/TabItem.test.tsx
  packages/ui/src/__tests__/molecules/Tabs/Tabs.test.tsx
  packages/ui/src/components/molecules/Tabs/TabItem.tsx
  packages/ui/src/components/molecules/Tabs/Tabs.tsx
  packages/ui/src/components/molecules/Tabs/index.ts
  packages/ui/src/stories/atoms/Checkbox.stories.ts
  packages/ui/src/stories/molecules/Tabs/Tabs.stories.tsx
Labels: enhancement, frontend, ui

#847 832-fefix-remove-unnecessary-props-from-components-with-shouldforwardprops
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/components/atoms/Button.tsx
  packages/ui/src/components/atoms/Input.tsx
  packages/ui/src/components/molecules/Modal.tsx
  packages/ui/src/styles/FlexBox.ts
Labels: bug, frontend

#858 fe-bug-export-checkbox-and-tabs-from-ui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/CheckBox.test.tsx
  packages/ui/src/__tests__/molecules/Tabs/TabItem.test.tsx
  packages/ui/src/__tests__/molecules/Tabs/Tabs.test.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/components/molecules/Tabs/index.ts
  packages/ui/src/components/molecules/index.ts
  packages/ui/src/stories/atoms/Checkbox.stories.ts
  packages/ui/src/stories/molecules/Tabs/Tabs.stories.tsx
Labels: bug, enhancement, frontend, ui

#874 854-be-sso-migration-of-status-management-functionality-into-the-sso
  back/CHANGELOG.md
  back/openapi.yaml
  back/package-lock.json
  back/package.json
  back/prisma/data/users.ts
  back/prisma/migrations/20240122155001_remove_status/migration.sql
  back/prisma/schema.prisma
  back/src/__tests__/globalSetup.ts
  back/src/__tests__/mocks/ssoServer.ts
  back/src/__tests__/users/patchUser.test.ts
  back/src/controllers/auth/authMeController.ts
  back/src/controllers/auth/loginController.ts
  back/src/helpers/sso/login.ts
  back/src/openapi/components/errorSchemas.ts
  back/src/openapi/components/responses/authMiddleware.ts
  back/src/openapi/config.ts
  back/src/openapi/routes/auth/login.ts
  back/src/schemas/users/userSchema.ts
  sso/CHANGELOG.md
  sso/db/init.sql
  sso/openapi.yaml
  sso/package-lock.json
  sso/package.json
  sso/src/__tests__/auth/login.test.ts
  sso/src/__tests__/globalSetup.ts
  sso/src/__tests__/user/patch.test.ts
  sso/src/controllers/auth/loginController.ts
  sso/src/openapi/components/errorSchemas.ts
  sso/src/openapi/components/responses.ts
  sso/src/openapi/config.ts
  sso/src/openapi/routes/auth/login.ts
  sso/src/schemas/user/userSchema.ts
Labels: enhancement, backend

#862 841 fe migrate counter to UI
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/__tests__/atoms/Counter.test.tsx
  packages/ui/src/__tests__/atoms/Spinner.test.tsx
  packages/ui/src/components/atoms/Counter.tsx
  packages/ui/src/components/atoms/Spinner.ts
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/stories/atoms/Counter.stories.ts
  packages/ui/src/stories/atoms/Icon.stories.ts
  packages/ui/src/stories/atoms/Spinner.stories.ts
Labels: enhancement, frontend

#886 885-fe-bug-export-molecules-from-packagesui
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/ui/src/index.ts
Labels: bug, frontend

#867 865-fe-migrate-user-image-to-ui
  packages/ui/CHANGELOG.md
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/rollup.config.js
  packages/ui/src/__tests__/atoms/Avatar.test.tsx
  packages/ui/src/components/atoms/Avatar/default.svg
  packages/ui/src/components/atoms/Avatar/index.tsx
  packages/ui/src/components/atoms/index.ts
  packages/ui/src/custom.d.ts
  packages/ui/src/stories/atoms/avatar/custom.svg
  packages/ui/src/stories/atoms/avatar/index.stories.tsx
Labels: enhancement, frontend

#898 Remove Link component
  front/CHANGELOG.md
  front/package.json
  front/src/__tests__/atoms/Link.test.tsx
  front/src/components/atoms/Link.tsx
  front/src/components/atoms/index.ts
Labels: frontend
